password plugin: better error message on constraint violation
roundcube/roundcubemail pull request #5727
Opened 2017-04-18 18:57 UTC by torbjo

If the password policy on the ldap server is violated when changing
password, report error as "constraint violation" instead of the
misleading "connection error".

Note: LDAP_CONSTRAINT_VIOLATION can be returned for multiple
reasons – not just password policy violation – but in this case
it's a pretty safe bet it's caused by a ppolicy violation.

Only tested with OpenLDAP (v2.4).

2017-04-19 09:52 UTC, alecpl requested changes

2017-04-19 09:52 UTC, alecpl commented on plugins/password/password.php
> +define('PASSWORD_LDAP_CONSTRAINT_VIOLATION', 5);
I think we could skip _LDAP in the constant name. Other drivers might also want to use it.

2017-04-19 18:36 UTC, torbjo commented on plugins/password/password.php
> +define('PASSWORD_LDAP_CONSTRAINT_VIOLATION', 5);
Sure. Have pushed fixed.

I was unsure about the naming of this one, so I defaulted to keeping it similar to the constant from ldap.h

2017-04-20 09:10 UTC, alecpl requested changes
You have to rename the constant in all places

2017-04-20 19:26 UTC, torbjo commented
Whops. My bad. Fixed.

2017-04-21 08:39 UTC, merged

2017-04-22 00:47 UTC, lbguilherme commented
Typo: Password constraint violation. Password probably ~to~ **too** weak.

2017-04-23 19:31 UTC, torbjo commented
Thanks.
Can I just push a fix to this branch/PR or should I create a new one?

2017-04-24 06:07 UTC, alecpl commented
A new one please. The typo is already fixed.