[html2text/plaintext] add inline links behavior
roundcube/roundcubemail pull request #6485
Opened 2018-10-19 10:18 UTC by nantkowiak

i added a new feature to display links besides there text instead of a linklist. similar to other mailtools (google, thunderbird, ...) which uses html2text functionality. additionally you can now control the html2text behavior via the config.

2021-07-22 11:59 UTC, homotechsual commented
What would be needed to unstick this? It would be a fantastic addition.

2021-07-24 06:44 UTC, alecpl requested changes
Also, it would be good to have some tests.

2021-07-24 06:44 UTC, alecpl commented on program/include/rcmail.php
> +            'links'             => $this->config->get('html2text_links', true),
Maybe instead of two options for link create one. I.e `html2text_links` would accept 3 values: 0 - no links, 1 - links at the end, 2 - links inline. Of course with BC where false = 0, true = 1.

2021-07-24 06:44 UTC, alecpl commented on program/include/rcmail.php
> +            'charset'           => $this->config->get('html2text_charset', RCUBE_CHARSET),
I would not allow to change this charset. Please, remove this option.

2021-07-24 06:44 UTC, alecpl commented on program/lib/Roundcube/rcube_html2text.php
> +     * @param boolean $do_links  Indicate whether a table of link URLs is desired
So, it would be bool|int. And we should create class constants LINKS_NONE=0, LINKS_END=1, LINKS_INLINE=2

2021-07-26 09:00 UTC, alecpl requested changes

2021-07-26 09:00 UTC, alecpl commented on program/include/rcmail.php
> +            'links'             => $this->config->get('html2text_links', rcube_html2text::LINKS_DEFAULT),
Remove extra spacing before =>.

2021-08-01 09:44 UTC, alecpl requested changes

2021-08-01 09:44 UTC, alecpl commented on tests/Framework/Html2text.php
> +        $ht = new rcube_html2text(null, false, rcube_html2text::LINKS_NONE);
You could leave `false` in a few places to have the BC check.

2021-08-01 09:44 UTC, alecpl commented on config/config.inc.php.sample
> +$config['html2text_width'] = 75;
The documentation should go to `defaults.inc.php`.

2021-08-02 09:14 UTC, nantkowiak commented on tests/Framework/Html2text.php
> +        $ht = new rcube_html2text(null, false, rcube_html2text::LINKS_NONE);
already done. see bc tests `test_links_bc_with_boolean` and `test_links_no_list_bc_with_boolean`

2021-08-04 08:37 UTC, merged