rewrite skin_logo config
roundcube/roundcubemail pull request #6983
Opened 2019-10-23 18:16 UTC by johndoh

for #6981 

various improvements to the skin_logo config option. the following keys are now supported:

```
skin:template[type]
skin:template
skin:*[type]
skin:*
skin[type]
*:template[type]
*:template
template[type]
template
*[type]
*
[type]
```

also I've improved the documentation in `defaults.inc.php`

2019-10-24 18:49 UTC, alecpl requested changes

2019-10-24 18:49 UTC, alecpl commented on tests/Rcmail/OutputHtml.php
> +             "elastic[small]"       => "img05",
`elastic[small]` is wrong. In this case you look for "elastic" template. This is confusing. I propose to allow skin name prefix with colon only. I.e. setting `[small]` logo in Elastic only would be `elastic:[small]` or `elastic:*[small]`

2019-10-24 18:49 UTC, alecpl commented on program/include/rcmail_output_html.php
> +    protected function get_template_logo($name = null, $type = null, $strict = false)
The $name argument is not used. I propose to get rid of it.

2019-10-24 19:25 UTC, johndoh commented on program/include/rcmail_output_html.php
> +    protected function get_template_logo($name = null, $type = null, $strict = false)
good point. I'll correct this

2019-10-24 19:29 UTC, johndoh commented on tests/Rcmail/OutputHtml.php
> +             "elastic[small]"       => "img05",
This PR makes `elastic[small]` and `elastic:*[small]` both valid. My aim was to allow for variations that people might use. but I understand your point may be `elastic:[small]` is more obvious than `elastic[small]`. Or may be all 3?

2019-10-25 06:04 UTC, alecpl commented on tests/Rcmail/OutputHtml.php
> +             "elastic[small]"       => "img05",
The `elastic[small]` option is confusing, because without colon it looks like `template[type]`. "Skin prefix has always a colon" rule should solve that.

2019-10-26 09:54 UTC, alecpl commented on program/include/rcmail_output_html.php
> +    protected function get_template_logo($type = null, $strict = false)
Now, while we're on it. The $strict argument does not make sense to me. Could we remove it?

2019-10-27 07:18 UTC, johndoh commented on program/include/rcmail_output_html.php
> +    protected function get_template_logo($type = null, $strict = false)
right, any time `$type` is set we can assume a strict match

2019-10-27 08:30 UTC, merged