improvements to options menu link template object
roundcube/roundcubemail pull request #7237
Opened 2020-02-22 13:06 UTC by johndoh

Here I propose 2 changes.

1) is to allow template object attributes to contain conditions or expressions as well as static values.
2) is to add some more parameters to the rcmail_options_menu_link template object and improve the flexibility for use both as part of the message list template object and as a standalone element.

These changes are backwards compatible.

(excerpt from #7195)

2020-03-14 10:53 UTC, alecpl requested changes

2020-03-14 10:53 UTC, alecpl commented on program/include/rcmail_output_html.php
> +            elseif (strpos($value, 'condition:') === 0) {
I would make these compare the `$key` not `$value`. Also, maybe it would be more convenient to use `exp:` and `cond:` prefix. And, because check_condition is the same as eval_expression, I think we only need one, `exp:`. Or maybe even as Vue does, only the colon character.

2020-03-14 10:53 UTC, alecpl commented on program/steps/mail/func.inc
> +            'class'    => $attrib['class'] ?: 'listmenu',
Well, that's not exactly backward compatible, but I think we can leave it this way.

2020-03-14 13:36 UTC, johndoh commented on program/include/rcmail_output_html.php
> +            elseif (strpos($value, 'condition:') === 0) {
I think `attribute-name="exp:!in_array('list_cols', (array)config:dont_override)"` is cleaner looking than `exp:attribute-name="!in_array('list_cols', (array)config:dont_override)"`

2020-03-14 19:29 UTC, alecpl commented on program/include/rcmail_output_html.php
> +            elseif (strpos($value, 'condition:') === 0) {
Using this on key is safer, i.e. using "exp:..." as a value that should be send to the browser will be problematic. Let's do ":attribute-name", some people should be familiar with such a way.

2020-03-15 08:37 UTC, johndoh commented on program/include/rcmail_output_html.php
> +            elseif (strpos($value, 'condition:') === 0) {
Changes done. I know its a slightly bigger change now foreach is faster than array_walk.

2020-03-15 08:56 UTC, merged