add some events and public methods to elastic ui.js
roundcube/roundcubemail pull request #7240
Opened 2020-02-22 13:18 UTC by johndoh

I'm not 100% if I've done this right but currently extending the Elastic skin is very tricky by adding a few public methods and JS even triggers I am to simplify that a bit.

If you do not like this approach please close this PR so I know to rethink.

(excerpt from #7195)

2020-03-14 11:13 UTC, alecpl requested changes
The general idea is all right. I'm not sure about one part, see inline comment.

2020-03-14 11:13 UTC, alecpl commented on skins/elastic/ui.js
> +        var ret = undefined;
`= undefined` is redundant.

2020-03-14 11:13 UTC, alecpl commented on skins/elastic/ui.js
> +        if ((ret = rcmail.triggerEvent('skin-menu-toggle', { props: p })) !== undefined) {
What use-case do you have for this whole code change?

2020-03-14 13:44 UTC, johndoh commented on skins/elastic/ui.js
> +        if ((ret = rcmail.triggerEvent('skin-menu-toggle', { props: p })) !== undefined) {
I would like to add option to the `messagelistmenu` dialog. To do that I need to be able to override the default handling so that I can set the current value of my field when the dialog is opened and read the value when the save button is clicked.

2020-03-15 09:09 UTC, alecpl commented on skins/elastic/ui.js
> +        if ((ret = rcmail.triggerEvent('skin-menu-toggle', { props: p })) !== undefined) {
I think you can do that using menu-open and menu-close events.

2020-03-15 09:49 UTC, johndoh commented on skins/elastic/ui.js
> +        if ((ret = rcmail.triggerEvent('skin-menu-toggle', { props: p })) !== undefined) {
menu-open might work but you have fish around to find the dialog and technically its fired before the dialog is created by Elastic (coz it also relies on this trigger). menu-close is not fired when the save button is clicked.

2020-03-15 11:45 UTC, johndoh commented
I think you are right about the `skin-menu-toggle` trigger it was duplicating functionality which already exists so I will find a different solution. In the mean time I added a small sanity check to the `menu_toggle()` function so that it does not error when there is a `menu-open` event with custom content (eg a menu added by a plugin).

2020-03-22 08:37 UTC, merged