Several Mailvelope-related fixes and features
roundcube/roundcubemail pull request #7348
Opened 2020-04-26 15:33 UTC by gurnec

Each commit is listed below. I'm open to any disagreements/critiques, so please fire away!

 * Let Mailvelope use sender's address to find pubkeys to check signatures

    Also remove the showExternalContent option which was removed from the Mailvelope API January 2019.

 * Fix size of Mailvelope iframe for PGP-inlined mail

    Emails with PGP attachments appear correctly [like this](https://user-images.githubusercontent.com/2966862/80312069-38324080-87b1-11ea-8ce9-88e263e1931b.png), but emails with the PGP in the message body before this commit looked squished [like this](https://user-images.githubusercontent.com/2966862/80312089-55670f00-87b1-11ea-8944-f0510c642a28.png). Now they both appear correctly. (Only tested in Chromium, sorry.)

 * Add missing `\`s to regexes in `rcube_check_email()`

    An unrelated minor bug fix, I can remove it if you'd prefer.

 * Avoid initializing Mailvelope if we don't need to

    Small efficiency fix, but it also makes the next two commits a bit smaller in scope.

 * Add config option to use Mailvelope Main Keyring

    Defaults to false for backwards compatibility. It's probably only useful for new installs. Related: #7157

 * Add config option for size of new Mailvelope keys

    Defaults to 4096 for backwards compatibility.

 * Always ask before discarding composed Mailvelopes

    The unpatched code appears to be intentionally *not* asking before discarding emails currently being composed. This does the exact opposite, which can be minorly annoying if one saves and then leaves while composing, but is much safer in other cases IMO. If others disagree, perhaps this could be a config option instead? Related: #7017

 * Don't warn to re-add attachments when restoring a Mailvelope draft

    Currently, if you save a Mailvelope email draft, and then select to edit it from your Drafts folder, the "Already uploaded attachments cannot be encrypted"... warning message is unnecessarily displayed.

2020-04-29 18:16 UTC, alecpl commented
Maybe we should make `mailvelope_main_keyring` a user preference. Assigning @thomascube for review.

2020-04-30 17:58 UTC, ryan77627 commented
Commit 2367aa7 is also working for Firefox 75, just verified it.

2020-05-10 08:39 UTC, alecpl commented
I cherry-picked fixes from here and backported to 1.4. The rest is a feature request. Please, rebase

2020-05-10 16:51 UTC, gurnec commented
@alecpl Thanks! Rebased, and I'll update the initial comment.

2020-05-10 17:06 UTC, gurnec commented
@alecpl One other quick note: I believe this one also qualifies as only-a-bugfix:

> * 9c38a44 Fix size of Mailvelope iframe for PGP-inlined mail
>
>    Emails with PGP *attachments* appear correctly [like this](https://user-images.githubusercontent.com/2966862/80312069-38324080-87b1-11ea-8ce9-88e263e1931b.png), but emails with the PGP *in the message body* before this commit looked squished [like this](https://user-images.githubusercontent.com/2966862/80312089-55670f00-87b1-11ea-8944-f0510c642a28.png). Now they both appear correctly. (Only tested in Chromium and Firefox 75, sorry.)

2020-06-09 10:53 UTC, thomascube commented
> Maybe we should make `mailvelope_main_keyring` a user preference. Assigning @thomascube for review.

@alecpl, @gurnec I agree this might be worth a user preference and not a fixed setting for all.
I wasn't aware that using the main keyring is now possible with Mailvelope. This would then fix #7157.

2020-06-14 17:01 UTC, thomascube commented
Question is just to which preference section that option could be added to...

2020-06-14 17:02 UTC, thomascube approved these changes

2020-06-28 09:42 UTC, thomascube commented
I suggest to merge this into master and then find the right place to add that user preference. The other changes are very valuable and should go into 1.5-beta

2020-06-29 13:53 UTC, trasherdk commented
Am I right in believing the `Mailvelope` thing is a browser extension? And that the usage is optional, as in a plugin?

2020-06-29 17:33 UTC, ryan77627 commented
Yes, Mailvelope is a browser plugin that does what the Enigma plugin does but client side (PGP Encryption and Decryption). It has an API that Roundcube integrates. Usage is only activated if the Mailvelope plugin is installed and your Roundcube domain has the API option turned on.

2020-07-03 09:53 UTC, alecpl requested changes

2020-07-03 09:53 UTC, alecpl commented on CHANGELOG
> +- Mailvelope: Fix size of iframe for PGP-inlined mail (#7348)
Please, rebase and put these on top of the changelog.

2020-07-03 09:53 UTC, alecpl commented on config/config.inc.php.sample
> +// Use the Main Keyring in Mailvelope? If not, use (creating if required)
Remove this. We want to have the sample config short.

2020-07-03 09:53 UTC, alecpl commented on program/js/app.js
> +      $('#messagebody').addClass('mailvelope');
You should not use skin-specific selectors. If needed add messagebody property to env via steps/mail/show.inc::rcmail_message_body().

2020-07-03 09:53 UTC, alecpl commented on program/js/app.js
> +    if (typeof window.mailvelope !== 'undefined')
wouldn't be better to just do `if (window.mailvelope)` ?

2020-07-18 06:34 UTC, alecpl commented
@gurnec Have you seen my last comments, will you be able to work on these?

2020-07-31 09:11 UTC, merged