support providing skins for plugins inside the main skin folder
roundcube/roundcubemail pull request #7445
Opened 2020-06-21 09:03 UTC by johndoh

I have been [working on](https://github.com/roundcube/plugin-installer/pull/24) the `plugin-installer`, trying to fix the reported issues. Then I thought it would be good if skins could be delivered through composer just like plugins. I added support for a package type of `roundcube-skin` and the installer moves it into the `skins/` folder rather than the `plugins/` folder.

If someone is going to create a new skin though they will want to add skin assets for plugins. At the moment that has to be in the skins folder of a plugin. So I [made](https://github.com/roundcube/plugin-installer/pull/24/commits/3cf1462ae6a860ea8f97753a9d79106eaba741df) the `plugin-installer` copy plugin skins into the `plugins/` folder.

I think this method of copying files around is rather messy so then I thought what if skins could hold plugin assets themselves. A lot of the existing code for extended skins can be leveraged to achieve this.

This is a non-breaking change (assuming properly coded plugins), the only special case is the `jqueryui` plugin which uses a `themes` dir rather than `skins` (ref #266) so I added support for custom dir names and skin names (because of the skin mapping feature of the `jqueryui` plugin).

Any assets in the `plugins/myplugin/skins/myskin/` folder take priority but if none are found then the code checks in `skins/myskin/plugins/myplugin/`. It also works with extended skins.

2020-06-28 09:45 UTC, thomascube commented
I think this makes sense.

2020-08-09 07:15 UTC, alecpl requested changes

2020-08-09 07:15 UTC, alecpl commented on plugins/jqueryui/jqueryui.php
>              self::$ui_theme = $ui_theme = $ui_map[$skin] ?: $skin;
So, we don't need that local $ui_theme variable. I'd remove it everywhere.

2020-08-09 07:15 UTC, alecpl commented on program/lib/Roundcube/rcube_plugin.php
> +        if ($fn[0] != '/' && !preg_match('|^https?://|i', $fn) && strpos($fn, $this->ID . '/') === false) {
I think, it would be better to use `!== 0` here, instead of `=== false`.

2020-08-09 07:15 UTC, alecpl commented on program/lib/Roundcube/rcube_plugin_api.php
> +        if ($fn[0] != '/' && !preg_match('|^https?://|i', $fn) && strpos($fn, '/' . $this->url) === false)
This change looks fishy to me.

2020-08-09 07:15 UTC, alecpl commented on program/lib/Roundcube/rcube_plugin.php
> +            $skins = (array) $skin_name;
Shouldn't that extend the `$skins` array, instead of replacing it? The comment says "Additional skin name".

2020-08-09 08:28 UTC, johndoh commented on program/lib/Roundcube/rcube_plugin_api.php
> +        if ($fn[0] != '/' && !preg_match('|^https?://|i', $fn) && strpos($fn, '/' . $this->url) === false)
I think I can change `strpos($fn, '/' . $this->url) === false` to `strpos($fn, 'skins/') !== 0`, is that better?

2020-08-09 08:44 UTC, johndoh commented on program/lib/Roundcube/rcube_plugin.php
> +        if ($fn[0] != '/' && !preg_match('|^https?://|i', $fn) && strpos($fn, $this->ID . '/') === false) {
!== will not work because of all the different possible paths e.g.:
```
skins/larry/style.css
plugin.js
js/plugin.js
skins/elastic/plugin.css
skins/elastic/plugins/plugin/plugin.css
skins/elastic/plugins/plugin/plugin.js
```
the idea is to make sure the plugin folder only gets added into the path if its not already there but I guess people could add a subfolder in their plugin folder with the same name and then this would fail.

perhaps this would be better `!preg_match("|^skins/[a-z0-9-_]+/plugins/$this->ID/|i", $fn)`?

2020-08-09 08:58 UTC, johndoh commented on program/lib/Roundcube/rcube_plugin.php
> +            $skins = (array) $skin_name;
the only use for this is in the jqueryui plugin which has its own skin map. its the comment which is misleading, I've corrected it.

2020-08-20 22:52 UTC, dereks commented
Thank you for submitting a Pull Request (PR) to the Roundcube GitHub project.

You are receiving this message because your PR has conflicts which need to be resolved. We are trying to catch up on our backlog of old PRs and get them merged in (where appropriate). Therefor, we request the following:

**Step 1.** Rebase from the latest Roundcube branch master into your PR.

```
git fetch upstream
git checkout your_feature_branch_name
git rebase upstream/master
git push -f origin your_feature_branch_name
```

**Step 2.** Re-test to make sure your new code still works as expected

**Step 3.** Comment back here once it has been tested and will merge cleanly.

Once this has been done we will treat it like a new Pull Request and consider it for acceptance.

Apologies for the inconvenience. Thank you for contributing to Roundcube!

2020-12-21 08:45 UTC, merged