elastic: make custom less files optional
roundcube/roundcubemail pull request #7497
Opened 2020-07-19 07:31 UTC by johndoh

Optional `@imports` where added in Less v2 which was released 5 years ago. So by bumping the min version up from 1 to 2 (v3 is already used in jsdeps) then the customisation files `_styles` and `_variables` can be renamed as dist files so they don't conflict with what people might have in their local repos.

the `-x` compression option does not work properly in current version of lessc so I have also update the readme to mention the clean-css plugin and changed the extension of the generated files to `.min.css` so that cssshrink.sh skips the already minified files.

2020-07-19 08:37 UTC, alecpl commented
1. I think that we can get rid of the .dist files. Just describe them in README.
2. After I upgraded less in my system, your commands give: "Unable to load plugin clean-css please make sure that it is installed under or at the same level as less". So, this is an additional complexity. Does clean-css minify the file better that cssshrink.sh? If it doesn't, maybe we should just not use that option, and minify with cssshrink.sh.

2020-07-19 09:02 UTC, johndoh commented
This is trivial but the current version of cssshrink.sh does not work with Elastic because Elastic CSS is in the styles folder not the root of the skin.

to fix you plugin error try running `npm install -g less-plugin-clean-css`.

minifying test on styles.css:
-x: 118,312B
cssshrink.sh: 118,291B
clean-css: 116,647B

2020-07-19 09:15 UTC, alecpl commented
OK. We can use clean-css, but please describe installation of less and clean-css in the README. We also have to install proper version for Travis.

2020-07-19 09:47 UTC, johndoh commented
I have added a little more detail to the note in the readme file. do you think it is enough?

But I'm stumped by Travis, may be this change has to wait until the Travis tests can be moved to a more modern distro, it looks like Ubuntu Trust has a very old node-less package.

2020-07-19 09:53 UTC, alecpl commented
Instead of installing the node-less package we could just run: `npm install --force -g less less-plugin-clean-css`.

That note should be enough.

2020-07-19 10:17 UTC, johndoh commented
Thanks for the tip, that did the trick. I left out the clean-css plugin because the Travis script does not minify the css.

2020-07-21 06:35 UTC, alecpl requested changes
Please, remove these .dist files and add a note to README.

2020-07-21 06:35 UTC, alecpl commented on skins/elastic/README.md
> +The can be installed using `npm install less-plugin-clean-css`)
"It can be..."

2020-07-21 10:29 UTC, johndoh commented on skins/elastic/README.md
> +The can be installed using `npm install less-plugin-clean-css`)
fixed

2020-07-22 00:26 UTC, trasherdk commented on skins/elastic/README.md
>      $ lessc --clean-css="--s1 --advanced" styles/embed.less > styles/embed.min.css
Shouldn't those double-quotes be single-quotes?

`lessc --clean-css='--s1 --advanced' styles/embed.less > styles/embed.min.css`

To prevent shell expansion.

2020-08-05 09:22 UTC, thomas-mc-work commented on skins/elastic/README.md
> +    $ lessc --clean-css="--s1 --advanced" styles/styles.less > styles/styles.min.css
What do the clean-css switches mean? I couldn't find them in their documentation.

2020-08-06 07:58 UTC, johndoh commented on skins/elastic/README.md
> +    $ lessc --clean-css="--s1 --advanced" styles/styles.less > styles/styles.min.css
Look a couple of lines down, its the config for the clean-css Less plugin which does the minifying

2020-10-08 13:48 UTC, merged