Improve preciseness of some PHPdoc annotations
roundcube/roundcubemail pull request #7809
Opened 2021-01-02 08:50 UTC by mstilkerich

Another few improvements to the type annotations to improve static analysis results.

2021-01-02 12:51 UTC, alecpl requested changes

2021-01-02 12:51 UTC, alecpl commented on program/lib/Roundcube/rcube_addressbook.php
> +     * @param int    $mode    Search mode. Sum of self::SEARCH_*.
Please, params descriptions should be aligned with each other.

2021-01-02 12:51 UTC, alecpl commented on program/lib/Roundcube/rcube_addressbook.php
> +     * @param string|string[] $required List of fields that cannot be empty
The code indeed accepts a string, but I would not advertise this possibility here.

2021-01-02 12:51 UTC, alecpl commented on program/lib/Roundcube/rcube_addressbook.php
> +     * @param string|string[] $fields   List of fields to search in
Please, take a look at rcube_contacts param descriptions. We should use similar here. I mean the description should say something about the type difference too.

2021-01-02 17:50 UTC, mstilkerich commented on program/lib/Roundcube/rcube_addressbook.php
> +     * @param int    $mode    Search mode. Sum of self::SEARCH_*.
Fixed

2021-01-02 17:54 UTC, mstilkerich commented on program/lib/Roundcube/rcube_addressbook.php
> +     * @param string|string[] $required List of fields that cannot be empty
From my viewpoint as developer of an implementation of this interface, I'm looking at this not as advertisement of possibilities but as required expected behavior that I have to implement. So unless roundcube guarantees not to use this interface with string parameters, it must be listed here.
Looking at the roundcube code, it seems to _exclusively_ use this parameter in its string form, I did not find a single use of the array variant:

```
./program/actions/mail/search_contacts.php:            $result = $source->search($afields, $search, $search_mode, true, true, 'email');
./program/actions/mail/autocomplete.php:                if ($result = $abook->search($fields, $search, $mode, true, true, 'email')) {
./program/actions/contacts/mailto.php:                $sources[] = $contacts->search($contacts->primary_key, $cid, 0, true, true, 'email');
./program/actions/contacts/photo.php:                    $result = $abook->search(['email'], $email, 1, true, true, 'photo');
```
Therefore, I would suggest to keep the interface definition as proposed.

2021-01-02 17:56 UTC, mstilkerich commented on program/lib/Roundcube/rcube_addressbook.php
> +     * @param string|string[] $fields   List of fields to search in
I adapted the texts from rcube_contacts. As the function is not very comprehensively specified, I also added more extensive description of my understanding that I gathered from studying the roundcube code. I you are open to such documentation, I would also contribute more in this direction for other functions of this interface, which would also help me to get a common understanding / agreement on the interface definition for addressbook implementations.

2021-01-02 17:57 UTC, mstilkerich commented
Thanks for your fast feedback, Alec. I really appreciate your responsiveness to pull requests. Please find my comments as replies to yours.

2021-01-07 20:58 UTC, alecpl requested changes

2021-01-07 20:58 UTC, alecpl commented on program/lib/Roundcube/rcube_result_set.php
> +     * @var int $count  The number of total records. Note that when only a subset of records of records is requested,
Variable name here is optional, so I propose to not use it. Also, the extra spaces between type and description are not needed.

2021-01-07 20:58 UTC, alecpl commented on program/lib/Roundcube/rcube_result_set.php
> +     * @var array $records The data records of he result set. May be a subset of the total records, e.g. for one page.
Typo: he -> the.

2021-01-07 20:58 UTC, alecpl commented on program/lib/Roundcube/rcube_result_set.php
>      public $count      = 0;
After adding the comment extra spaces here are not needed and should be removed.

2021-01-07 20:58 UTC, alecpl commented on program/lib/Roundcube/rcube_addressbook.php
> +     * Mode "Direct ID search" - when $fields is either 'ID' or $this->primary_key
Nicely written, but the use of word "mode" might be confused with the $mode param below.

2021-01-08 08:24 UTC, mstilkerich commented on program/lib/Roundcube/rcube_result_set.php
> +     * @var int $count  The number of total records. Note that when only a subset of records of records is requested,
Fixed

2021-01-08 08:24 UTC, mstilkerich commented on program/lib/Roundcube/rcube_result_set.php
> +     * @var array $records The data records of he result set. May be a subset of the total records, e.g. for one page.
Fixed

2021-01-08 08:27 UTC, mstilkerich commented on program/lib/Roundcube/rcube_result_set.php
>      public $count      = 0;
I hope I understood correctly that this is about the spaces preceeding the assignment - I removed these at all places where I added comments.

2021-01-08 08:37 UTC, mstilkerich commented on program/lib/Roundcube/rcube_addressbook.php
> +     * Mode "Direct ID search" - when $fields is either 'ID' or $this->primary_key
Good point. I couldn't think of a suitable alternative term for mode, so I removed terming the different modes of operation (ID search etc.) as mode.

2021-01-09 09:01 UTC, alecpl requested changes

2021-01-09 09:01 UTC, alecpl commented on program/lib/Roundcube/rcube_result_set.php
> +     * @var int The number of total records. Note that when only a subset of records of records is requested,
Last thing. Duplicated "of records".

2021-01-09 09:04 UTC, mstilkerich commented on program/lib/Roundcube/rcube_result_set.php
> +     * @var int The number of total records. Note that when only a subset of records of records is requested,
Thanks, fixed.

2021-01-09 09:05 UTC, merged