retry login if IMAP Servers timeout.
roundcube/roundcubemail pull request #7844
Opened 2021-01-23 03:27 UTC by hefee

When connection fails in a recoverable way, we should retry to connect
to the server again. This should help in cases, when the connection to the IMAP server is not 100% stable.

In #7402 it was suggested to implement this retry feature as plugin. In order to create such a plugin, it needs the information about the last login attempt. The last attempt is added to the `data['conn']`.

We also face the issue, that we only call `storage_connect` before the try to connect. That's why we need a way to stop instantly when no new attempt should be done.

(followup of #7402, #5393)

2021-01-23 08:31 UTC, alecpl requested changes

2021-01-23 08:31 UTC, alecpl commented on plugins/retrylogin/readme.md
> +  $config['retrylogin_max_attempts'] = 5;
Wouldn't be better to specify this as a time interval?

2021-01-23 08:31 UTC, alecpl commented on plugins/retrylogin/composer.json
> +  "name": "retrylogin",
I'm not sure I like the plugin name. Maybe `imap_reconnect` or `imap_retry` would be better.

2021-01-23 08:31 UTC, alecpl commented on plugins/retrylogin/LICENSE
> +                    GNU GENERAL PUBLIC LICENSE
We don't need the LICENSE file here.

2021-01-23 08:31 UTC, alecpl commented on program/lib/Roundcube/rcube_imap.php
> +                'conn'           => $this->conn,
$this->conn is a public property so you don't really need this.

2021-01-23 08:31 UTC, alecpl commented on plugins/retrylogin/retrylogin.php
> +        rcube::write_log('imap','Connecting to IMAP server attempt:' . $args['attempt']);
We write to imap log only in debug mode. And in this mode we already have "Connecting to..." in the log. So, I would just remove this.

2021-01-23 08:31 UTC, alecpl commented on plugins/retrylogin/retrylogin.php
> +        rcube::write_log('imap','Connecting to IMAP server attempt:' . $args['attempt']);
Remove this write_log.

2021-01-23 08:31 UTC, alecpl commented on program/lib/Roundcube/rcube_imap.php
> +            if ($attempt > 1 && !data['retry']) {
You don't need this `if` statement. We check `retry` flag in the while statement below. You just set it appropriately from the plugin.

2021-01-23 13:16 UTC, hefee commented on plugins/retrylogin/retrylogin.php
> +        rcube::write_log('imap','Connecting to IMAP server attempt:' . $args['attempt']);
I use roundcube 1.3.15 in production and there I do not see any "Connecting to..." line in imap log, nor can I see that this line is somewhere created in `program/lib/Roundcube/rcube_imap.php`. But things may change deeper in the stack.

I cannot really see in the communication with the server and I think it is good to know that the retry plugin is doing further attempts to login:

```
[23-Jan-2021 03:11:01 +0100]: <goet9ij9> Connecting to IMAP server attempt:1
[23-Jan-2021 03:11:01 +0100]: <goet9ij9> [5055] S: * OK [CAPABILITY IMAP4rev1 SASL-IR LOGIN-REFERRALS ID ENABLE IDLE LITERAL+ STARTTLS LOGINDISABLED] Dovecot (Debian) ready.
[23-Jan-2021 03:11:01 +0100]: <goet9ij9> [5055] C: A0001 STARTTLS
[23-Jan-2021 03:11:01 +0100]: <goet9ij9> [5055] S: A0001 OK Begin TLS negotiation now.
[23-Jan-2021 03:11:01 +0100]: <goet9ij9> [5055] C: A0002 CAPABILITY
[23-Jan-2021 03:11:01 +0100]: <goet9ij9> [5055] S: * CAPABILITY IMAP4rev1 SASL-IR LOGIN-REFERRALS ID ENABLE IDLE LITERAL+ AUTH=PLAIN AUTH=LOGIN
[23-Jan-2021 03:11:01 +0100]: <goet9ij9> [5055] S: A0002 OK Pre-login capabilities listed, post-login capabilities have more.
[23-Jan-2021 03:11:01 +0100]: <goet9ij9> [5055] C: A0003 ID ("name" "Roundcube" "version" "1.3.15" "php" "7.3.19-1~deb10u1" "os" "Linux" "command" "/?_task=login")
[23-Jan-2021 03:11:01 +0100]: <goet9ij9> [5055] S: * ID ("name" "Dovecot")
[23-Jan-2021 03:11:01 +0100]: <goet9ij9> [5055] S: A0003 OK ID completed.
[23-Jan-2021 03:11:01 +0100]: <goet9ij9> [5055] C: A0004 AUTHENTICATE PLAIN ****** [37]
[23-Jan-2021 03:11:03 +0100]: <goet9ij9> [5055] S: A0004 NO [AUTHENTICATIONFAILED] Authentication failed.
[23-Jan-2021 03:11:03 +0100]: <goet9ij9> Connecting to IMAP server attempt:2
[...]
[23-Jan-2021 03:11:09 +0100]: <goet9ij9> Connecting to IMAP server attempt:3
```

2021-01-23 13:18 UTC, hefee commented on program/lib/Roundcube/rcube_imap.php
> +                'conn'           => $this->conn,
But how do the plugin get access to the current instance of rcube_imap?

2021-01-23 13:54 UTC, hefee commented on program/lib/Roundcube/rcube_imap.php
> +            if ($attempt > 1 && !data['retry']) {
here is an example without this if statement:
*attempt=1, retry= True
  -> do a `$this->conn->connect`
  -> while loop decide to go on
*attempt=2 checks the last attempt and decides not to continue retry=False
  -> still do a  `$this->conn->connect`
  -> while loop stops

as you see without this if statement another reconnect attempt is executed, but this is not what we want to do. The problem we face is that we call the storage_connect hook only before we connect and not after it. This if statement makes it possible to stop immediately and not do an unexpected reconnect attempt.

I know it is a behavior change, so we could also use another key in the array to tell to stop immediately.

2021-01-23 14:16 UTC, hefee commented on plugins/retrylogin/readme.md
> +  $config['retrylogin_max_attempts'] = 5;
You mean define X attempts per Y mins or you want to define the sleep between the attempts?

2021-01-23 16:59 UTC, alecpl commented on program/lib/Roundcube/rcube_imap.php
> +                'conn'           => $this->conn,
rcube::get_storage()

2021-01-23 17:00 UTC, alecpl commented on plugins/retrylogin/retrylogin.php
> +        rcube::write_log('imap','Connecting to IMAP server attempt:' . $args['attempt']);
https://github.com/roundcube/roundcubemail/blob/1eebfd723bc6706d76c280dbeaf708d4ba8f010d/program/lib/Roundcube/rcube_imap_generic.php#L1043 If you really think it is useful in non-debug mode, make it a config option in the plugin.

2021-01-23 17:05 UTC, alecpl commented on program/lib/Roundcube/rcube_imap.php
> +            if ($attempt > 1 && !data['retry']) {
I see, but I still don't like it. I'll consider this. BTW, there's missing `$` character.

2021-01-23 17:06 UTC, alecpl commented on plugins/retrylogin/readme.md
> +  $config['retrylogin_max_attempts'] = 5;
I meant to define maximum time from the request start to the moment you give up. I think it might be more useful that a number of attempts, but maybe it does not really matter.

2021-01-23 18:36 UTC, hefee commented on plugins/retrylogin/retrylogin.php
> +        rcube::write_log('imap','Connecting to IMAP server attempt:' . $args['attempt']);
Okay I think this is enough.

2021-01-23 18:48 UTC, hefee commented on program/lib/Roundcube/rcube_imap.php
> +                'conn'           => $this->conn,
It needs to be `rcmail::get_instance()->get_storage()` at least this this line I can find in other plugins.

2021-01-23 19:06 UTC, hefee commented on plugins/retrylogin/readme.md
> +  $config['retrylogin_max_attempts'] = 5;
The current bugs #7402, #5393 both around of flaky connection to IMAP server, where attempts seems the better solution. Maybe the word timeout in title is misleading. It also handles the case, when the IMAP server closes with ""Empty startup greeting". A timeout setting would mean that the plugin needs to store the the timestamp of each first attempt to calculate the timeout, this makes the plugin more complex and we need to store this additional data.

2021-01-23 19:06 UTC, hefee commented on program/lib/Roundcube/rcube_imap.php
> +            if ($attempt > 1 && !data['retry']) {
Fixed the `$` character.

I can fully understand that it does not looks not very clean. If you have any other idea...

2021-01-24 08:16 UTC, alecpl requested changes

2021-01-24 08:16 UTC, alecpl commented on plugins/imap_reconnect/imap_reconnect.php
> +    switch ($storage->conn->errornum) {
You could also use more official api: $storage->get_error_code().

2021-01-24 08:16 UTC, alecpl commented on plugins/imap_reconnect/config.inc.php.dist
> +?>
No closing tags, please.

2021-01-24 08:16 UTC, alecpl commented on plugins/imap_reconnect/composer.json
> +  "name": "imap reconnect",
4 spaces indent, please.

2021-01-24 08:16 UTC, alecpl commented on plugins/imap_reconnect/imap_reconnect.php
> +  private $max_attempts;
4 spaces indent, please.

2021-01-24 11:44 UTC, hefee commented on plugins/imap_reconnect/config.inc.php.dist
> +?>
done.

2021-01-24 11:44 UTC, hefee commented on plugins/imap_reconnect/imap_reconnect.php
> +    switch ($storage->conn->errornum) {
done.

2021-02-06 07:28 UTC, alecpl commented
Now I have a question. Why would IMAP connection be unstable and not others. Shouldn't we implement the same for at least SMTP? What about managesieve?

Maybe the plugin should be named just 'reconnect', so we can extend it with code for other connection types in future, if needed.

2021-02-06 13:03 UTC, hefee commented
> Now I have a question. Why would IMAP connection be unstable and not others. Shouldn't we implement the same for at least SMTP? What about managesieve?

Well I havn't seen the root of issue for quite a while, but when we debugged the issue, we didn't found out why the IMAP connection were closed by the IMAP server only that ~1% failing and retry solved the issue. I think it may happen also for SMTP and managesieve, but as the amount of connections to SMTP and managesieve are several of magnitudes lower than IMAP, it is properly harder to see the issue.

> Maybe the plugin should be named just 'reconnect', so we can extend it with code for other connection types in future, if needed.

ACK. I understood you correctly, that I do not need to invenst time to add these connection types?

2021-02-06 15:45 UTC, alecpl approved these changes

2021-02-06 15:46 UTC, merged