Add support for XCLIENT ADDR and LOGIN extension
roundcube/roundcubemail pull request #7893
Opened 2021-02-19 09:58 UTC by kwiatek6324

PR created from issue: #6411

PR Checks if XCLIENT extension is active.

Roundcube will send XCLIENT ADDR=x.y.z.z when configured and XCLIENT ADDR extension is available
In special configuration we want smtp server to use originating IP for policy checking instead of IP from web server.

Roundcube will send XCLIENT LOGIN=webmailuser@domain.com when configured and XCLIENT LOGIN extension is available
In some situation (f.e. SSO) there is no possibility use smtp_user and smtp_pass, but we want to process outgoing message as authenticated.

2021-02-20 07:50 UTC, alecpl requested changes

2021-02-20 07:50 UTC, alecpl commented on program/lib/Roundcube/rcube_smtp.php
> +
1. Your code style is really bad.
2. The config options are bool, so `==1` is not needed.
3. The regexp for ADDR will match also DESTADDR. I would propose to use explode() and in_array_nocase() instead of regexps. And yes, we should use case insensitive comparison.
4. If the IP address is an IPv6 address, it should be prefixed with `IPV6:`. If for some reason remote_addr() returns no address `[UNAVAILABLE]` label should be used.
5. Move the code to a separate method.
6. Limit number of config->get() calls.

2021-02-20 10:59 UTC, kwiatek6324 commented on program/lib/Roundcube/rcube_smtp.php
> +
@alecpl Corrected version.

2021-02-21 07:24 UTC, alecpl commented
The error handling is probably redundant, and your code style is still not acceptable.

2021-04-18 07:15 UTC, alecpl requested changes
Fix code style, please.

2021-04-25 08:01 UTC, merged