Clean Tr: in subject header
roundcube/roundcubemail pull request #7929
Opened 2021-03-09 10:43 UTC by tpayen

Some french mail clients use "Tr:" instead of "Fwd:" as forward indicator in subject. 
I don't know if there is such exceptions in others languages in which case this maybe worth the use of a configuration parameter instead of an hardcoded regex ?

2021-03-09 10:56 UTC, alecpl commented
We have an old ticket for this: #4981. I think it should be a config option with a default that contains most common cases.

2021-03-09 14:58 UTC, tpayen commented
Hi Alec,
I've added a new commit to support config options for subject prefixes.
4 more options are possible : 
 - default_forward_prefix (default = 'Fwd:') : the default prefix when forwarding an email
 - default_response_prefix (default = 'Re:') : the default prefix when responding to an email
 - subject_response_prefixes (default = ['Re:']) : the prefixes list to clean for responses
 - subject_forward_prefixes (default = ['Fwd:', 'Fw:']) : the prefixes list to clean for forwarded messages

2021-03-13 08:08 UTC, alecpl requested changes

2021-03-13 08:08 UTC, alecpl commented on program/include/rcmail_sendmail.php
> +        return rcmail::get_instance()->config->get('default_response_prefix', 'Re:') . ' ' . $subject;
I would remove `default_` from these option names. Also, what if it is set to an empty string? You should trim the return value.

2021-03-13 08:08 UTC, alecpl commented on program/lib/Roundcube/rcube_imap_generic.php
> +                        $value = preg_replace('/^('.implode('|', $data).')+/i', '', $value);
So, we have similar code in a few places. I would suggest to unify and de-duplicate this.

I.e. create `rcube_utils::remove_subject_prefix($subject, $mode)` where mode would be 'reply', 'forward' or 'both'.

2021-03-15 17:45 UTC, tpayen commented
Thanks for these relevant remarks. I've added a new commit to add the `rcube_utils::remove_subject_prefix` function and make everything a little cleaner

2021-03-21 13:55 UTC, alecpl requested changes

2021-03-21 13:55 UTC, alecpl commented on program/include/rcmail_sendmail.php
>          $subject = preg_replace('/\s*\([wW]as:[^\)]+\)\s*$/', '', $subject);
How about moving this into remove_subject_prefix() (in 'reply' mode)?

2021-03-21 13:55 UTC, alecpl commented on program/lib/Roundcube/rcube_utils.php
> +    public static function remove_subject_prefix($subject, $mode = 'both')
How do you feel about adding some tests in tests/Framework/Utils.php?

2021-03-21 13:55 UTC, alecpl commented on program/lib/Roundcube/rcube_utils.php
> +            $reply_prefixes = rcmail::get_instance()->config->get('subject_reply_prefixes', ['Re:']);
Let's do `$config = rcmail::get_instance()->config` first and then use it to make the code shorter.

2021-03-21 13:55 UTC, alecpl commented on program/lib/Roundcube/rcube_utils.php
> +            return $prefix.':|'.$prefix.'\[\d\]:|'.$prefix.'-\d:';
Add a space between dots, please. Or everything using double-quote'd syntax.

2021-04-20 13:44 UTC, tpayen commented on program/lib/Roundcube/rcube_utils.php
> +    public static function remove_subject_prefix($subject, $mode = 'both')
I'll try but I don't promise anything  ;-)
I'll do an independent commit for this

2021-04-25 07:41 UTC, merged