Support class and realname props for a folder
roundcube/roundcubemail pull request #7937
Opened 2021-03-11 15:08 UTC by tpayen

Hooks like `render_mailboxlist` allow a plugin to customize the folder tree but are limited for the folder css class and the folder display name. 

With this PR a plugin can add a `class` prop and a `realname` boolean prop to customize the CSS class of the folder and the display name.

2021-03-13 08:00 UTC, alecpl requested changes

2021-03-15 14:13 UTC, tpayen commented
Hi @alecpl thanks for your response. I took your comments into account in my last commit

2021-04-18 06:52 UTC, alecpl requested changes

2021-04-18 06:52 UTC, alecpl commented on program/include/rcmail_action.php
> +            if (!$realnames && ($folder_class = self::folder_classname($folder['id'], isset($folder['class']) ? $folder['class'] : null)) && $rcmail->text_exists($folder_class)) {
This line is too long now.

2021-04-18 06:52 UTC, alecpl commented on program/include/rcmail_action.php
> +     * @param string $fallback fallback Folder CSS class name
Two spaces after $fallback, and start the description with a capital letter.

2021-04-18 06:52 UTC, alecpl commented on program/include/rcmail_action.php
> +            $realname     = $realnames || isset($folder['realname']) ? $folder['realname'] : false;
Here you need to add brackets. Or, it should be:
```
$realname     = isset($folder['realname']) ? $folder['realname'] : $realnames;
```

2021-04-25 07:28 UTC, alecpl requested changes

2021-04-25 07:28 UTC, alecpl commented on program/include/rcmail_action.php
> +            if (isset($folder_class) && !$realname && $rcmail->text_exists($folder_class)) {
Here we don't need isset().

2021-04-25 07:28 UTC, alecpl commented on program/include/rcmail_action.php
> +            if (isset($folder_class) && !$realname && $rcmail->text_exists($folder_class)) {
Here we don't need isset().

2021-05-07 15:53 UTC, merged