More extensive documentation for query-related rcube_addressbook API
roundcube/roundcubemail pull request #7958
Opened 2021-03-18 16:19 UTC by mstilkerich

This adds a bit more extensive documentation on the query-related APIs of rcube_addressbook which should be helpful for developers of addressbook plugins.

Please mind the two `FIXME` markers in the comment, where I could not determine the expected behavior from studying the roundcube code and hope you can help out with the expected behavior here.

2021-04-24 07:41 UTC, alecpl requested changes

2021-04-24 07:41 UTC, alecpl commented on program/lib/Roundcube/rcube_addressbook.php
> +     * @param int $mode     Search mode. Sum of rcube_addressbook::SEARCH_*.
Please, align the names and descriptions.

2021-04-24 07:41 UTC, alecpl commented on program/lib/Roundcube/rcube_addressbook.php
> +     * active group (see set_group()), and the required contact properties (see $requiredProps), if applicable.
`$requiredProps`? I don't see that anywhere.

2021-04-24 07:41 UTC, alecpl commented on program/lib/Roundcube/rcube_addressbook.php
> +     * @param int    $subset Only return this number of records of the current page, use negative values for tail
While on this. Could you add the third param that exists in rcube_contacts::list_records(), please?

2021-05-15 07:31 UTC, mstilkerich commented on program/lib/Roundcube/rcube_addressbook.php
> +     * subset or not? Currently it is not considered, i.e. first will always be a multiple of the page size
Ok, I adapted accordingly.

2021-05-15 07:37 UTC, mstilkerich commented on program/lib/Roundcube/rcube_addressbook.php
> +     * FIXME The purpose of SEARCH_GROUPS is not clear to me and not considered.
Thanks, I added this. I guess this flag combined with direct ID search might turn up unexpected records, as there might be groups and contacts having the same ID.

2021-05-15 07:37 UTC, mstilkerich commented on program/lib/Roundcube/rcube_addressbook.php
> +     * @param int $mode     Search mode. Sum of rcube_addressbook::SEARCH_*.
done

2021-05-15 07:37 UTC, mstilkerich commented on program/lib/Roundcube/rcube_addressbook.php
> +     * active group (see set_group()), and the required contact properties (see $requiredProps), if applicable.
Oops, that is an internal option of the carddav plugin that I copied the description from. Removed mentioning of that option.

2021-05-15 07:37 UTC, mstilkerich commented on program/lib/Roundcube/rcube_addressbook.php
> +     * @param int    $subset Only return this number of records of the current page, use negative values for tail
done

2021-05-15 07:48 UTC, mstilkerich commented
Addressed your comments and rebased against current master.

2021-05-15 07:57 UTC, alecpl commented on program/lib/Roundcube/rcube_addressbook.php
> +    abstract function list_records($cols = null, $subset = 0, $nocount = false);
This introduced a bug: `PHP Fatal error:  Declaration of rcube_ldap::list_records($cols = null, $subset = 0) must be compatible with rcube_addressbook::list_records($cols = null, $subset = 0, $nocount = false) in /home/travis/build/roundcube/roundcubemail/program/lib/Roundcube/rcube_ldap.php on line 598`
The same in example_addressbook plugin. Could you fix these, please?

2021-05-15 08:10 UTC, mstilkerich commented on program/lib/Roundcube/rcube_addressbook.php
> +    abstract function list_records($cols = null, $subset = 0, $nocount = false);
Fixed

2021-05-15 12:15 UTC, merged