Spelling
roundcube/roundcubemail pull request #8001
Opened 2021-04-14 13:42 UTC by jsoref

This PR corrects misspellings identified by the [check-spelling action](https://github.com/marketplace/actions/check-spelling).

The misspellings have been reported at https://github.com/jsoref/roundcubemail/commit/f37abf09a2666bc873f178f0b1d3f6fbc0ef6d00#commitcomment-49507654

The action reports that the changes in this PR would make it happy: https://github.com/jsoref/roundcubemail/commit/4ba60339937e0dd0492ca963b548558f0d0067bf

2021-04-14 13:52 UTC, jsoref reviewed
~I should note that there appears to be a cross link between this project and localizations.~

~As such, I think I tried to avoid "fixing" misspelled localization keys.~

~Personally, I dislike misspelled localization keys. While it's certainly easier to find them in source files (since they're unique), it makes it hard for a localizer to understand what they're localizing.~

Oops. I was actively ignoring the localizations directory. Curse of tooling doing what one tells it to do.

2021-04-14 13:52 UTC, jsoref commented on INSTALL
> +With Lighttpd the addition of Expire: tags by mod_expire is incompatible with
This is a brand

2021-04-14 13:52 UTC, jsoref commented on INSTALL
> +There are two forms of optimization here, compression and caching, both aimed
It felt like this project leaned towards en-US, so I've included a couple of commits which harmonize en-GB/en-US.

Obviously I can drop anything, and as things are by word family, dropping a couple of families is trivial.

2021-04-14 13:52 UTC, jsoref commented on config/defaults.inc.php
> +// By default IMAP capabilities are read after connection to IMAP server
The past tense of read is read.

2021-04-14 13:52 UTC, jsoref commented on plugins/http_authentication/logout.html
>  </body>
I try not to use a text editor on files, so the missing new-line-at-eof is retained, but personally I dislike them.

2021-04-14 13:52 UTC, jsoref commented on plugins/managesieve/managesieve.js
> +    // Set activate/deactivate set
I'm not particularly certain about this one

2021-04-14 13:52 UTC, jsoref commented on plugins/password/config.inc.php.dist
> +// Example: ['ldap1.example.com', 'ldap2.example.com'];
I'm assuming that since the label is misspelled the dns is also unintentionally misspelled.

If you need additional domains, there are others available:
https://tools.ietf.org/html/rfc2606#section-3

2021-04-14 13:52 UTC, jsoref commented on plugins/password/config.inc.php.dist
> +// kpasswd Driver options
brand

2021-04-14 13:52 UTC, jsoref commented on plugins/password/drivers/dovecot_passwdfile.php
> +        // read the entire mail user file
It was a toss up with `mailuserfile`

2021-04-14 13:52 UTC, jsoref commented on plugins/password/password.php
> +            $curpwd = $confirm ? rcube_utils::get_input_value('_curpasswd', rcube_utils::INPUT_POST, true, $charset) : $sesspwd;
everything else seems to use `sess*`

2021-04-14 13:52 UTC, jsoref commented on program/js/googiespell.js
> +    var req_text = this.escapeSpecial(this.original_text),
If this or anything else is a third party module, I can trivially exclude it; let me know.

2021-04-14 13:52 UTC, jsoref commented on program/lib/Roundcube/rcube_csv2vcard.php
> +        'pager_number'      => "Pager Number",
This is the only change that broke a test.

2021-04-14 13:52 UTC, jsoref commented on program/lib/Roundcube/rcube_imap.php
> +     * @return bool True on success, False on failure
I'm guessing here

2021-04-14 13:52 UTC, jsoref commented on program/lib/Roundcube/rcube_spellchecker.php
> +     * @return bool True when no misspelling found, otherwise false
Yes, people do tend to misspell misspelling

2021-04-14 13:52 UTC, jsoref commented on program/lib/Roundcube/rcube_spellchecker.php
> + * Helper class for spellchecking with GoogieSpell and PSpell support.
this is a brand

2021-04-14 13:52 UTC, jsoref commented on skins/larry/templates/settings.html
> +<h2 id="aria-label-prefsection" class="boxtitle"><roundcube:label name="section" /></h2>
I'm guessing here

2021-04-14 13:52 UTC, jsoref commented on tests/Framework/Html2text.php
> +        $this->assertContains('QUOTED TEXT NO END TAG FOUND', $res, 'No quoting on invalid html');
It's hard to tell if things want `quote` or `quota` in this repository.

2021-04-14 13:52 UTC, jsoref commented on tests/src/Csv2vcard/tb_plain.vcf
> +TEL;TYPE=pager:pager
This fixes the broken test noted above.

2021-04-17 09:01 UTC, alecpl requested changes

2021-04-18 02:01 UTC, jsoref commented on CHANGELOG
> +- Changed strong tooltips for message browse buttons (closes #757)
I'm thinking of just dropping the word entirely.

2021-04-18 06:43 UTC, merged