Add exec_hook to new_user_dialog
roundcube/roundcubemail pull request #8023
Opened 2021-04-23 09:50 UTC by Virinum

Executes `identity_update` hook before updating identity.

My goal is to update the provided name in hMailServer. For this I'm listening for `identity_update` hook. But it doesn't get called. So I've added a manual exec_hook to plugin `new_user_dialog`.

I was inspired by plugin `new_user_identity`.

I'm not quite sure if handling `abort` this way is correct.

2021-04-23 09:57 UTC, alecpl commented
This is incomplete. Please, take a look at how the hook is handled in program/actions/settings/identity_save.php. Specifically, 'abort', 'message', 'result' and 'record' properties.

2021-04-23 12:42 UTC, Virinum commented
Sorry, but I don't know what you want me to do. I had a look at `identity_save.php`.

**Email conversion:** Wasn't done before either
**Abort:** Is handled
**Result:** I don't know what you mean
**Record:** I don't know what you mean
**Message:** Wasn't done before either

Like I said, I looked at the plugin `new_user_identity` and there it is handled nearly the same way:
https://github.com/roundcube/roundcubemail/blob/b4b50b87b35e5a50bd94666057d72ce716082dd7/plugins/new_user_identity/new_user_identity.php#L102-L114

2021-04-25 09:05 UTC, alecpl commented
This is how this hook is handled in the other place (the relevant parts that are wrong or missing here):
```php
    if (!$plugin['abort']) {
        $updated = $rcmail->user->update_identity($iid, $save_data);
    }
    else {
        $updated = $plugin['result'];
    }

    if ($updated) {
        $rcmail->output->show_message('successfullysaved', 'confirmation');
    }
    else {
        $error = !empty($plugin['message']) ? $plugin['message'] : 'errorsaving';
        $rcmail->output->show_message($error, 'error', null, false);
    }
```

2021-04-25 18:37 UTC, Virinum commented
It's no problem to include this. But it will add a success message, which it didn't had before. Is that wanted?

And am I right that it's also missing in `new_user_identity` plugin?

2021-04-26 05:50 UTC, alecpl commented
> It's no problem to include this. But it will add a success message, which it didn't had before. Is that wanted?

The success message is already there.
```
 $rcmail->output->show_message('successfullysaved', 'confirmation');
```
> And am I right that it's also missing in `new_user_identity` plugin?

Yes, but there it is not possible (or much harder) to make use of all hook arguments.

2021-04-26 10:14 UTC, Virinum commented
> The success message is already there.

You're right. I've overlooked this.

Hope it's now complete. Learned a lot about hooks. Thanks for your support and all your work!

2021-05-02 10:25 UTC, alecpl requested changes

2021-05-02 10:25 UTC, alecpl commented on plugins/new_user_dialog/new_user_dialog.php
> +            $plugin = $rcmail->plugins->exec_hook('identity_update', array(
Please, use short array syntax.

2021-05-02 10:25 UTC, alecpl commented on plugins/new_user_dialog/new_user_dialog.php
> +                $rcmail->user->save_prefs(['newuserdialog' => null]);
I would move this save_prefs() call below, under `if ($updated)`.

2021-05-02 10:25 UTC, alecpl commented on plugins/new_user_dialog/new_user_dialog.php
> +                //show error
add a space after `//`

2021-05-06 10:06 UTC, merged