Update and rename CHANGELOG to CHANGELOG.md
roundcube/roundcubemail pull request #8048
Opened 2021-05-06 09:52 UTC by EwoutH

Converts the Changelog to markdown syntax.

2021-05-06 10:00 UTC, alecpl requested changes
Access to the new file will have to be blocked in the .htaccess file.

2021-05-06 10:00 UTC, alecpl commented on CHANGELOG.md
> +- Fix HTML sanitizer to skip <! node type X > in output (#4932)
Changes like these aren't acceptable.

2021-05-06 10:44 UTC, EwoutH commented
@alecpl Thanks for your comments! I did should have used stricter requirements on my regex replace to remove the dashed lines (-----), that is now fixed. I also fixed a few `<!>` cases that got recognized as comments, and replaces a ' that should have been a `.

2021-05-08 08:37 UTC, alecpl commented
Please, resolve conflicts and I'll merge it.

2021-05-10 08:23 UTC, merged