Some minor improvements for password plugin
roundcube/roundcubemail pull request #8402
Opened 2022-01-17 14:13 UTC by matwey

* Allow LDAP URI to communicate via UNIX socket (when available)
* Allow SASL bind for LDAP search queue.

2022-01-22 09:03 UTC, alecpl commented
Why sasl bind for search and not also for record modification? It would be good to describe new options in config.inc.php.dist. And it looks to me that 'password_ldap_uri' does not work in the 'ldap' driver. This needs to be fixed or noted.

2022-01-23 16:00 UTC, matwey commented
Thank you for the feedback!

- I think it is a good idea to enable SASL also for password update.
- `config.inc.php.dist` update is also on the way.
- Indeed, `ldap` driver uses deprecated library which doesn't support LDAP URI.

2022-04-10 17:32 UTC, alecpl requested changes

2022-04-10 17:32 UTC, alecpl commented on plugins/password/config.inc.php.dist
> +$config['password_ldap_uri'] = null;
Many other options e.g. `imap_host` support URI syntax, therefore I think it would make sense to support URIs in `password_ldap_host` instead.

2022-04-10 17:32 UTC, alecpl commented on plugins/password/drivers/ldap_simple.php
> +        switch ($rcmail->config->get('password_ldap_search_bind_method')) {
Do we really need a separate method/mech/realm for search? Is it a real use-case to have a different method for both binds?

2022-06-06 19:37 UTC, matwey commented
Sorry for this long delay. I am working on changes.

2023-04-02 10:55 UTC, matwey commented on plugins/password/config.inc.php.dist
> +$config['password_ldap_uri'] = null;
`password_ldap_host` is used instead of `password_ldap_uri`

2023-04-02 10:55 UTC, matwey commented on plugins/password/drivers/ldap_simple.php
> +        switch ($rcmail->config->get('password_ldap_search_bind_method')) {
`password_ldap_search_`/`password_ldap_admin_` renamed to `password_ldap_`

2023-05-28 08:38 UTC, merged