Add config option for request uri field (#8738)
roundcube/roundcubemail pull request #8770
Opened 2022-10-31 20:46 UTC by thomascube

This can be used to read a custom header sent by a reverse proxy to resolve the absolute path to Roundcube.

Resolves issue #8738

2022-11-01 07:07 UTC, alecpl commented
When we deal with proxy headers we should probably check `proxy_whitelist` (see rcube_utils for a reference usage).

Also, wouldn't it be enough to just set the path in the config for simplicity? I guess use of a header covers mixed or multi-host setups, but are they common?

2022-11-02 20:50 UTC, thomascube commented
I don't know how common it is to use (different) subpaths on a reverse proxy. The proposed solution with a config option `request_uri_field` is a generic approach to resolve issues with wrong guessing of the request URL. It's not directly related to x-fowarded-* headers and thus the `proxy_whitelist` check might not be appropriate.

2022-11-03 06:31 UTC, alecpl requested changes
Looks like two tests fail.

2022-11-03 06:31 UTC, alecpl commented on program/include/rcmail.php
> +    protected function get_requesr_uri_field() {
A typo in the function name. Also, add a new line before `{`

2022-11-03 06:31 UTC, alecpl commented on program/include/rcmail.php
> -            if (isset($_SERVER['REQUEST_URI'])) {
You moved that block to another place, I'll have to test this PR.

2022-11-03 06:31 UTC, alecpl commented on config/defaults.inc.php
> +$config['request_uri_field'] = 'REQUEST_URI';
I wonder whether this makes sense to be set at all. And whether this option is useful without proxy. Maybe it should be `$config['proxy_uri_field'] = null;` or `$config['request_path'] = null;` I'm not sure.

2022-11-06 21:06 UTC, thomascube commented on program/include/rcmail.php
> -            if (isset($_SERVER['REQUEST_URI'])) {
Yes that was indented in order to make this work also for the `$absolute || $full` mode.

2022-11-06 21:12 UTC, thomascube commented on config/defaults.inc.php
> +$config['request_uri_field'] = 'REQUEST_URI';
Depending on the PHP/webserver configuration the superglobal fields with path info may vary. The fact that we check for `REDIRECT_SCRIPT_URL` or `SCRIPT_NAME` already in the code underlines that. And there's `PATH_INFO` or `PHP_SELF` out there, too. Using a generic config option might help mitigating other potential problems with PHP environments not only related to reverse proxies.

2022-11-11 11:25 UTC, alecpl approved these changes

2022-11-11 11:26 UTC, alecpl commented
Approved. Though I'd have to find out why I still have `./phpunit` instead of `/vendor/bin/phpunit` on my setup.

2022-11-23 10:23 UTC, ghnp5 commented
Hey guys. Thank you for the fix. If this was approved, can this be merged so that this can go on the next release, please? 😊
Cheers!

2022-11-23 20:05 UTC, merged

2022-12-20 08:05 UTC, msimerson commented on config/defaults.inc.php
> +$config['request_uri_field'] = 'REQUEST_URI';
Big +1 from me for declaring exactly what the request path base should be. It will work reliably in any environment and doesn't require sending additional mostly duplicated and mostly useless tokens with every proxied HTTP request.

```diff
- $config['request_path'] = null;
+ $config['request_path'] = '/rcmail';
```

It's explicit. There's no parsing of it required.

2023-01-08 08:59 UTC, alecpl commented
I renamed the option to `request_path` and added possibility to set it just to a real path. `$_SERVER` field is also supported.

2023-01-20 19:37 UTC, ghnp5 commented
Hey. Any update on when will this be released to the Docker version? I'm using the latest version of Roundcube and this is still broken. I haven't been able to use Roundcube at all since this has been broken. Thank you very much!