add script to add identity
roundcube/roundcubemail pull request #8839
Opened 2022-12-29 18:34 UTC by vladasko-g

2023-01-01 12:32 UTC, alecpl requested changes
We should also check the `identities_level` option. It may disallow some actions.

2023-01-01 12:32 UTC, alecpl commented on bin/addidentity.sh
> +        'x' => 'dry-run',
'dir' and 'dry-run' aren't used here. Also, why are you using both getopt() and rcube_utils::get_opt()? Please, ose rcube_utils::get_opt() only.

2023-01-01 12:32 UTC, alecpl commented on bin/addidentity.sh
> +
You should copy the copyright header from other scripts, please.

2023-01-01 12:32 UTC, alecpl commented on bin/addidentity.sh
> +<?php
I'd start the PHP script just after  the shebang.

2023-01-01 12:32 UTC, alecpl commented on bin/addidentity.sh
> +} else {
Please, 4-space indentation.

2023-01-01 12:32 UTC, alecpl commented on bin/addidentity.sh
> +function get_host($args)
We're doing the same in deluser.sh. I guess we could de-duplicate this and create rcube_utils::get_imap_host_opt().

2023-01-01 12:32 UTC, alecpl commented on bin/addidentity.sh
> +  $new_identity['standard'] = $options['S'];
If you allow setting this flag you should unset this flag from the existing default identity, if such exists. I.e. you should use `rcube_user::set_default()` and not make it part of the `$options` array.

2023-01-01 12:32 UTC, alecpl commented on bin/addidentity.sh
> +  $new_identity['html_signature'] = $options['H'];
Please, make sure this is either '1' or '0'.

2023-01-02 16:01 UTC, vladasko-g commented on bin/addidentity.sh
> +        'x' => 'dry-run',
thanks for all the useful feedback, I forgot to mark this as draft, I'll update the PR

2023-01-24 14:51 UTC, vladasko-g commented on bin/addidentity.sh
> +
updated

2023-01-24 14:51 UTC, vladasko-g commented on bin/addidentity.sh
> +<?php
updated

2023-01-24 14:51 UTC, vladasko-g commented on bin/addidentity.sh
> +} else {
updated

2023-01-24 14:51 UTC, vladasko-g commented on bin/addidentity.sh
> +function get_host($args)
I moved this part to utils, but only changed the usage here

2023-01-24 14:52 UTC, vladasko-g commented on bin/addidentity.sh
> +  $new_identity['html_signature'] = $options['H'];
updated

2023-01-24 14:52 UTC, vladasko-g commented on bin/addidentity.sh
> +        'x' => 'dry-run',
updated

2023-01-25 18:45 UTC, vladasko-g commented
moved here https://github.com/roundcube/roundcubemail/pull/8887

2023-01-25 18:45 UTC, closed without merging