add loading message to mail and contacts list
roundcube/roundcubemail pull request #9027
Opened 2023-06-04 09:16 UTC by johndoh

for https://github.com/roundcube/roundcubemail/issues/9006

adds support for 2 additional labels into the Elastic skin `data-label-msg-loading` and `data-label-msg-empty` on list objects and uses those in the mail and addressbook templates to display a loading message in the list while the request is running.

this does not break any, BC. `data-label-msg` is still supported for simpler lists

2024-05-07 16:08 UTC, pabzm approved these changes
Looks good and works, thank you very much!

2024-05-07 16:12 UTC, pabzm commented
(@alecpl Just for clarity: I'm reviewing things but am currently not merging until you've had a chance to add your thoughts or we a grooved into a new workflow.)

2024-06-02 05:48 UTC, alecpl requested changes

2024-06-02 05:48 UTC, alecpl commented on skins/elastic/ui.js
> +            $('[data-label-msg],[data-label-msg-loading],[data-label-empty]').filter('ul,table').each(function () {
In templates you use `data-label-msg-empty` not `data-label-empty`.

2024-06-02 05:48 UTC, alecpl commented on skins/elastic/ui.js
>                          ) {
code style

2024-06-02 05:48 UTC, alecpl commented on skins/elastic/ui.js
> +                            msg = table.data('label-msg-loading');
It might be better to display "Searching..." when searching. Also, do we really need to display anything if there is a "Loading..."/"Searching..." message at the bottom?

2024-06-02 09:28 UTC, johndoh commented on skins/elastic/ui.js
> +                            msg = table.data('label-msg-loading');
I've made it say "searching...". I could remove the message but I guess people could miss the one in the bottom right?

2024-12-02 07:16 UTC, pabzm commented
@alecpl Please respond in the open thread of this PR. (I'll take over and decide on my own after one more week of silence.)

2024-12-02 07:16 UTC, pabzm commented
/remind me to merge this in one week

2024-12-04 17:12 UTC, johndoh commented
i have simplified the change. i think the important thing is the "list is empty" message does not display while the loading or searching actions are running

2025-01-03 12:00 UTC, pabzm commented
@johndoh Thank you for reducing your change to a state that's agreeable to all!

Could you fix the message of the first commit, please? (Contains a backslash instead of a quotation mark)

2025-01-03 14:57 UTC, johndoh commented
@pabzm fixed, sorry I didn't notice that before and thanks for the changelog text

2025-01-03 15:49 UTC, merged

2025-01-03 15:50 UTC, pabzm commented
@johndoh I allowed myself to resolve the conflict, since it was trivial and was caused by the Changelog line I wrote.

Thanks again for this contribution!

2025-01-08 08:23 UTC, alecpl commented
I'd prefer PRs to be squashed on merge.