oauth improvements
roundcube/roundcubemail pull request #9217
Opened 2023-11-16 00:44 UTC by EdouardVanbelle

* Add `oauth_config_uri` to parse the .well-known/openid-configuration and discover `oauth_*_uri`
  * Add `oauth_lotgout_uri` support of OIDC Back-Channel Logout (security improvement) (credit: @Westie)
  * Add support of OAUTHBEARER 
  * Fix: missing config `oauth_provider_name` in rcmail_oauth's constructor
  * Improvement: move display to the rcmail_oauth class and use `loginform_content` hook

2023-11-16 00:47 UTC, EdouardVanbelle commented
Dear team I a proposing you this patch to improve the OIDC use, I am currently using it for my personal use on the 1.6.5 version

I would like to thanks also @Westie for his work (I included it in this PR)

Let me know if you prefer non squashed PR

Kind regards
Edouard

2023-11-16 18:24 UTC, EdouardVanbelle commented
Hello I am going to check these two requests:

- https://github.com/roundcube/roundcubemail/issues/9109
- https://github.com/roundcube/roundcubemail/issues/9110

I guess only 1 is satisfied here

2023-11-16 19:26 UTC, alecpl requested changes

2023-11-16 19:26 UTC, alecpl commented on program/include/rcmail_oauth.php
> +        if ( !empty($config_uri)) {
that extra space all over the place needs to go out.

2023-11-16 19:26 UTC, alecpl commented on program/include/rcmail_oauth.php
> +    protected $prefered_auth = 'XOAUTH2';
`auth_type` would be better.

2023-11-16 20:03 UTC, EdouardVanbelle commented on config/defaults.inc.php
> +// Optional or Optional if $oauth_config_uri is specified: Endpoint for OIDC Logout propagation
result of a 2 o'clock commit ;)

2023-11-16 20:12 UTC, EdouardVanbelle commented on program/include/rcmail_oauth.php
> +        if ( !empty($config_uri)) {
you mean you prefer I move the highlighted block in a protected discover() method and call it in constructor ?

2023-11-18 16:03 UTC, azmeuk commented
Thank you very much for this patch! This would also fix #8201.

2023-11-18 16:23 UTC, azmeuk commented on config/defaults.inc.php
> +$config['oauth_logout_uri'] = null;
Why not call this var `oauth_end_session_endpoint` to fit to the OIDC spec vocabulary?

2023-11-18 16:24 UTC, azmeuk commented on config/defaults.inc.php
> +$config['oauth_logout_uri'] = null;
:thinking: Actually I don't know, `oauth_logout_uri` is similar to the other vars in rouncube :man_shrugging:

2023-11-18 17:17 UTC, EdouardVanbelle commented on config/defaults.inc.php
> +$config['oauth_logout_uri'] = null;
I kept same vocabulary as the current one, and @alecpl is right we need to setup a cache to avoid unnecessary call to OIDC

2023-11-18 17:29 UTC, azmeuk commented
I have tested this PR. Discovery works well!

As `id_token` is needed to pass as an `id_token_hint` parameter in the IdP end_session_endpoint, the `refresh_access_token` method is automatically called at logout since the `id_token` is absent from the session. I find this very strange to actually need to refresh a token just to logout, and invalid the token a few seconds after.

It was discussed a few years ago in #8214, at the time the maintainers preferred not to keep the id_token in the session. @thomascube would you reconsider this? I don't know if that was for security reasons, but nowadays with [RFC9068](https://www.rfc-editor.org/rfc/rfc9068.html) and people using JWT access tokens containing more or less the same payload than the `id_token`, I don't know if this is still relevant.

2023-11-18 17:36 UTC, azmeuk commented on program/include/rcmail_oauth.php
> +        ];
Out of curiosity, why not adding `client_id` and a `state` parameter here?

2023-11-18 17:46 UTC, EdouardVanbelle commented on program/include/rcmail_oauth.php
> +        ];
I did not challenged this part, need to check RFCs :)

2023-11-18 17:49 UTC, EdouardVanbelle commented
As we have the discovery, I took opportunity to fetch jwks (certificates) to verify JWT signatures, it is important for backchannel call to trust foreign calls

A future PR will come, for manual setup it will be config option `oauth_jwks_uri`

2023-11-18 17:59 UTC, azmeuk commented
I think I met one weak point: if the `refresh_access_token` returns `false` (because of wrong credentials or IdP misconfiguration for instance, or expired refresh token), then `$_SESSION['oauth_token']['id_token']` fails, and the roundcube user stays logged.

If `refresh_access_token` fails for whatever reason, maybe fill `$this->logout_redirect_url` anyways (after all the spec indicates the `id_token_hint` is *recommended* but not *mandatory*). 
Perhaps the `logout_hint` parameter would be useful in that situation? However I am not sure which value it should have. The obvious one is the email because it is one thing we are sure that roundcube has, but this may not be the value expected by the IdP. I don't know.

2023-11-18 18:31 UTC, EdouardVanbelle commented
@azmeuk I will check your remarks, currently the `refresh_token` is saved which is more sensitive than the `id_token`
I consider in a such case that we could store `id_token` too via the `encrypt()` method

2023-11-18 19:10 UTC, azmeuk commented
One last thing. On my setup, it seems that `id_token` is always null, even after calling `refresh_access_token`. After having a look at the `refresh_access_token` method, I cannot see anything that would save the `id_token` in `$_SESSION`, unlike `request_access_token`.

Looking closer at [the OIDC spec](https://openid.net/specs/openid-connect-core-1_0.html#RefreshTokenResponse), it seems the refresh token request should not return an id_token anyways:

> Upon successful validation of the Refresh Token, the response body is the Token Response of [Section 3.1.3.3Successful Token Response](https://openid.net/specs/openid-connect-core-1_0.html#TokenResponse) except that it might not contain an id_token.

Thus, to be able to use `id_token_hint`, it seems that keeping the `id_token` somewhere is actually mandatory.

2023-11-19 23:05 UTC, EdouardVanbelle commented
here is some improvements:

-  add cache to Discovery and JWKS
- add debug, activated vi òauth_debug` = true
- improve refresh token
- fetch sub (will be used later)
- fix leak of access_token
- use firebase/php-jwt JWT livrary and check signature if `oauth_jwks_uri` present
- provide `id_token_hint` and `client_id` on OpenID Connect RP-Initiated Logout

@azmeuk if you test you can activate the debug option

2023-11-19 23:17 UTC, EdouardVanbelle commented on program/include/rcmail_oauth.php
> +        ];
you now have the recommended options ;)

2023-11-22 11:34 UTC, azmeuk commented
Hi @EdouardVanbelle, I will try to test this soon.
The PR has become quite large. I wonder if splitting it up would not make the whole process easier for maintainers? :shrug:

2023-11-22 18:26 UTC, EdouardVanbelle commented
Hello @azmeuk ,  I pushed the version with the backchannel logout, you can add in your IDP a callback to `/index.php/oauth/backchannel` to test the functionality 

regarding the pull request need to check with @alecpl
I don't really know how to plug a such page which requires no session, and the way I did it may be an ugly hack

due to sensitivity of this patch it could be time to add tests before and after this patch, for that I need to learn how to code in php :) 

Right now I considered that it is overkill to redevelop a full JWT parser, so I used `firebase/php-jwt` which breaks current compatibility with **php 7.3**

2023-11-24 23:33 UTC, EdouardVanbelle commented
Hello @alecpl let me know if you need to split the pull request or rebase/squash it to make it more easier to review
I will appreciate any suggestion on how to catch a call for the backchannel url rather than the hack I did

2023-11-25 08:24 UTC, alecpl requested changes

2023-11-25 08:24 UTC, alecpl commented on index.php
> +    $_SERVER['REQUEST_URI'] === '/oauth/backchannel' )) {
I'm not very familiar with our OAuth related code.

Here I don't fully understand what is the hack? We already use `PATH_INFO` instead of `REQUEST_URI` in include/iniset.php, and it sets the task/action accordingly. Task will be overwritten in set_task(), but action should stick, so all we need is a code below this existing block:
```
// handle oauth login requests
else if ($RCMAIL->task == 'login' && $RCMAIL->action == 'oauth' && $RCMAIL->oauth->is_enabled()) {
    $oauth_handler = new rcmail_action_login_oauth();
    $oauth_handler->run();
}
```
similar to this, but with `$RCMAIL->action == 'backchannel'`. 

If the `$_SERVER['REQUEST_URI'] === '/oauth/backchannel'` part is required, I'd set action=backchannel  in the startup hook.

2023-11-25 08:24 UTC, alecpl commented on index.php
> +    $oauth_handler = new rcmail_action_oauth_backchannel();
Please, make it `rcmail_action_login_oauth_backchannel`. I see it's not exactly 'login', but it's related and I'd prefer to have them both in program/actions/login folder.

2023-11-25 08:24 UTC, alecpl commented on program/actions/oauth/backchannel.php
> +                    'message' => "oidc backchannel called without any parameter", // FIXME show IP from
`rcube_utils::remote_ip()`

2023-11-25 08:24 UTC, alecpl commented on program/include/rcmail_oauth.php
> +    //FIXME: php seems supporting enum
We're not ready to jump to PHP 8.1 yet, I think. We might decide later what will be the minimum for the next Roundcube version, but it would rather be 8.0, I suppose.

2023-11-25 08:24 UTC, alecpl commented on program/include/rcmail_oauth.php
> +                            'message' => 'key '.$config_key.' not found in answer of '.$config_uri,
For such I usually prefer double quotes and variables in form of `{$var}` inside.

2023-11-25 08:24 UTC, alecpl commented on program/include/rcmail_oauth.php
> +            $this->jwks['expires']=time() + self::JWKS_CACHE_TTL;
Code style. space `=` space.

2023-11-25 08:24 UTC, alecpl commented on program/include/rcmail_oauth.php
> +
Code style. Please remove all unneeded empty lines, like here and in the beginning of the method body. Also, `if` space `(`, and I see an unneeded space after `(` in a few places.

2023-11-25 14:32 UTC, EdouardVanbelle commented on index.php
> +    $oauth_handler = new rcmail_action_oauth_backchannel();
I used `oauth` task because I saw in `program/include/rcmail.php`    
```
public static $main_tasks = ['mail','settings','addressbook','login','logout','utils','oauth','dummy'];
```

I am correcting following your recommendations

2023-12-03 14:23 UTC, alecpl requested changes

2023-12-03 19:16 UTC, EdouardVanbelle commented on program/include/rcmail_oauth.php
> +                    $this->cache->set("discovery", $data);
ok, I will apply same behavior with `jwks` cache

2023-12-03 19:23 UTC, EdouardVanbelle commented on program/include/rcmail_oauth.php
> +        $this->jwks = $this->cache ? $this->cache->get("jwks") : null;
will use same mechanism for discovery:
```php
  $key_cache = "jwks".md5($jwks_uri);
```

2023-12-03 21:06 UTC, EdouardVanbelle commented on program/include/rcmail_oauth.php
> +        $min_refresh_interval = $this->rcmail->config->get('min_refresh_interval');
here I do the assumption that user don't do any action (passive on his browser)
so I am using the refresh frequency to be sure the access_token will be refreshed before it's expiration, it is not the best way to do and saw that user can change his refresh frequency via $a_user_prefs['refresh_interval']

need to do deeper tests to be sure that if I don't do this trick, that the refresh_token will occurs **before** the next IMAP sync

2023-12-03 21:55 UTC, EdouardVanbelle commented on index.php
> +else if ($RCMAIL->task == 'login' && $RCMAIL->action == 'backchannel' && $RCMAIL->oauth->is_enabled()) {
I have this working on `rcmail_oauth`

```php 
    public function startup(array $args)
    {
        if (!$this->is_enabled()) {
            return $args;
        }

        if ($args['task'] == 'login' && $args['action'] == 'oauth') {
            // handle oauth login requests
            $oauth_handler = new rcmail_action_login_oauth();
            $oauth_handler->run();
        }
        else if ($args['task'] == 'login' && $args['action'] == 'backchannel') {
            // handle oauth login requests
            $oauth_handler = new rcmail_action_login_oauth_backchannel();
            $oauth_handler->run();
        }
        else if ($args['task'] == 'logout') {
            //handle only logout task
            $this->handle_logout();
        }

        return $args;
    }
```

which remove oauth code in index.php

I could also migrate `rcmail_action_login_oauth` and `rcmail_action_login_oauth_backchannel` into `rcmail_oauth`
Doing this rcmail_oauth becomes an autonomous class but this code is becoming deeply long...

That said, it seems that that rcmail_oauth can become a plugin 
Let me know your preferences

2023-12-04 19:27 UTC, EdouardVanbelle commented on program/include/rcmail_oauth.php
> +    public function get_auth_type()
I have this kind of POC:

```diff
@@ -965,18 +952,24 @@ class rcube_imap_generic
         $auth_methods = [];
         $result       = null;

         // check for supported auth methods
-        if (!$auth_method || $auth_method == 'CHECK') {
+        if (!$auth_method || $auth_method == 'CHECK' || $auth_method == 'CHECK_OAUTH') {
             if ($auth_caps = $this->getCapability('AUTH')) {
                 $auth_methods = $auth_caps;
             }

+            if ($auth_method == 'CHECK_OAUTH') {
+                $all_methods = ['XOAUTH2','OAUTHBEARER'];
+            }
+            else {
                 // Use best (for security) supported authentication method
                 $all_methods = ['DIGEST-MD5', 'CRAM-MD5', 'CRAM_MD5', 'PLAIN', 'LOGIN'];

                 if (!empty($this->prefs['gssapi_cn'])) {
                     array_unshift($all_methods, 'GSSAPI');
                 }
+            }

             foreach ($all_methods as $auth_method) {
                 if (in_array($auth_method, $auth_methods)) {
```

doing this I set auth_type='CHECK_OAUTH' and let library choosing the authentification method according server's capabilities

2023-12-05 17:38 UTC, alecpl commented on program/include/rcmail_oauth.php
> +    public function get_auth_type()
Yes. Makes sense. I think we'll need this also for Sieve and SMTP. One thing though, I don't like `CHECK_OAUTH`. I'd make it just `OAUTH`?

2023-12-05 18:49 UTC, EdouardVanbelle commented on program/include/rcmail_oauth.php
> +    public function get_auth_type()
We are now in the most complexe situation: where we have to find the best naming :)
ok for OAUTH

I submitted yesterday some merge requests for that purpose on Sieve & SMTP libraries

Do you agree to submit this change via another pull request ? 
Current MR is already including too many features

2023-12-05 18:50 UTC, alecpl commented on program/include/rcmail_oauth.php
> +    public function get_auth_type()
Sure.

2023-12-10 22:48 UTC, EdouardVanbelle commented on program/include/rcmail_oauth.php
> +    public function get_auth_type()
Hello @alecpl, I took a look on `program/actions/login/oauth.php` code is 90% same as the block 
```php
if ($RCMAIL->task == 'login' && $RCMAIL->action == 'login') {
...
``` 
in `index.php` which means if this part is changed, it may break oauth login

I will check to move logic into `authenticate` hook

2023-12-12 00:11 UTC, EdouardVanbelle commented on program/include/rcmail_oauth.php
> +    public function get_auth_type()
Here is a work in progress: (based on current merge request) https://github.com/EdouardVanbelle/roundcubemail/commit/dcfd29d318ef1feefc5d8c800a08d9684a242259
I am going to mark this thread as resolved
Once merged we will focus on this other commit

2023-12-12 03:47 UTC, Neustradamus commented
To follow

2023-12-12 21:36 UTC, EdouardVanbelle commented
Hello @alecpl you have the next coming changes on another branch (once this one is approved)
https://github.com/EdouardVanbelle/roundcubemail/compare/master...EdouardVanbelle:roundcubemail:feat/hooks-and-oauth?expand=1

- choose the most appropriate auth mechanism for Sieve, IMAP and SMTP (will require latest libraries versions)
- simplify action/login/oauth in order to use hooks

2023-12-13 08:20 UTC, alecpl commented
@EdouardVanbelle So, the last part here that is not clear is that one with 'min_refresh_interval'.

Since you already know this code better than me, could you take a look at #9244 for feedback, please.

2023-12-13 23:16 UTC, EdouardVanbelle commented on program/include/rcmail_oauth.php
> +        $min_refresh_interval = $this->rcmail->config->get('min_refresh_interval');
Good catch, I mixed up `min_refresh_interval` and `refresh_interval`, now corrected

2023-12-16 16:25 UTC, alecpl commented
Please, fix the code style issues. We deployed code style checking in CI.

2023-12-16 18:11 UTC, EdouardVanbelle commented
@alecpl here it is !

2023-12-17 08:13 UTC, merged

2023-12-17 08:18 UTC, alecpl commented
@EdouardVanbelle Thank you for this work and I'm waiting for more!

2023-12-17 15:09 UTC, EdouardVanbelle commented
Thank you @alecpl  !
I prepare the next merge request
This also close this request: https://github.com/roundcube/roundcubemail/issues/9110

2023-12-17 20:15 UTC, Neustradamus commented
@EdouardVanbelle: Good job!

2024-06-08 16:51 UTC, oculos commented
@EdouardVanbelle Could you share a bit how to configure logout for keycloak? I've updated Roundcube, and attempted to use the new configs, but I can't seem to log off.

2024-06-10 18:02 UTC, EdouardVanbelle commented
Hello @oculos , here is my configuration:

tip concerning your `oauth_config_uri`: if you open this url in your browser you should have a json containing all your OIDC config

### Roundcube config:
(on my side I have enabled the debugging)

```php
$config['oauth_debug'] = true;
$config['oauth_provider'] = 'generic';
$config['oauth_provider_name'] = 'Vanbelle';
$config['oauth_client_id'] = 'YOUR-CLIENT-ID';
$config['oauth_client_secret'] = '#######';
$config['oauth_config_uri'] = 'https://YOUR-KEYCLOAK-DOMAIN/realms/YOUR-REALM/.well-known/openid-configuration';
$config['oauth_verify_peer'] = true;
$config['oauth_scope'] = "email openid";
$config['oauth_auth_parameters'] = [];
$config['oauth_identity_fields'] = ['email'];
// setup to true once config ok to remove user/pass prompt and redirect to oauth login
$config['oauth_login_redirect'] = false;
$config['oauth_cache'] = 'db';
$config['oauth_cache_ttl'] = '1d';
```


### Keycloak config:
```
General Settings
    Client ID: YOUR-CLIENT-ID
    Root URL : https://YOUR-ROUNDCUBE-DOMAIN/
    Home URL : https://YOUR-ROUNDCUBE-DOMAIN/
    Valid redirect URIs : https://YOUR-ROUNDCUBE-DOMAIN/index.php/login/oauth
    Valid post logout redirect URIs : https://YOUR-ROUNDCUBE-DOMAIN/?_task=logout
    Web origins : YOUR-ROUNDCUBE-DOMAIN
    Admin URL : https://YOUR-ROUNDCUBE-DOMAIN/

Capability config
    Client authentication : On
    Authorization : Off
    Authentication flow
        [X] Standard flow
        [ ] Direct access grants  <------ BEWARE: use it only if you need your MTA has a proxy in user/password gateway, usefull for a transition, I do not recommand it.
        [ ] Implicit flow
        [X] Service accounts roles
        [ ] OAuth 2.0 Device Authorization Grant
        [ ] OIDC CIBA Grant

Logout settings
    Front channel logout : Off
    Backchannel logout URL : https://YOUR-ROUNDCUBE-DOMAIN/index.php/oauth/backchannel
    Backchannel logout session required : On
    Backchannel logout revoke offline sessions : Off
```

### Debugging backchannel


To try backchannel logout: If you are on your Keycloak account in user:
https://YOUR-KEYCLOAK-DOMAIN/realms/YOUR-REALM/account/#/ > logout

on your roundcube's log directory, if you enabled debug on config (set `oauth_debug` to `true`), you should have:
```
$ tail -f oauth.log
[10-Jun-2024 17:30:34 +0000]: <0mb25nud> DEBUG: [ip=<IP FROM KEYCLOAK SERVER> sub=- ses=-] backchannel: logout event received, schedule a revocation for token's sub: <ID Of THE SUB>
[10-Jun-2024 17:30:39 +0000]: <6m4s24lp> DEBUG: [ip=<IP OF THE CUSTOMER (next refresh)> (X-Forwarded-For: 88.175.55.47) sub=<ID Of THE SUB> ses=6da52dcb-855b-4776-a813-6552f1275f2e] abort, token for sub <ID OF THE SUB> has been revoked
```

### Debugging postlogout

once logged in Roundcube, just logout, it should propagate to Keycloak the logout request:

```
$ tail -f oauth.log
[10-Jun-2024 17:38:41 +0000]: <oetqnpfm> DEBUG: [ip=<IP OF THE CUSTOMER>  sub=<ID Of THE SUB> ses=fa2a21b9-5f69-43c5-829a-a2bf1c22c1b7] creating logout call: https://YOUR-KEYCLOAK-DOMAIN/realms/YOUR-REALM/protocol/openid-connect/logout?post_logout_redirect_uri=https%3A%2F%2FYOUR-ROUNDCUBE-DOMAIN%2F%3F_task%3Dlogout&client_id=YOUR-CLIENT-ID&id_token_hint=YOUR-TOKEN
```

and your session on keycloak should be kicked

2024-06-10 20:30 UTC, oculos commented
Thanks a lot @EdouardVanbelle 
What is weird here is that I don't think roundcube is indeed picking up the configurations.
As I said, having only the `oauth_config_uri` doesn't work, even if the link is correct (I clicked on it from the terminal and it does show all the links - it's just that Roundcube doesn't pick them.

Not even the debug is working: 

```
-rw-r--r--  1 www-data www-data 677K Jun 10 12:03 errors.log
-rw-r--r--  1 www-data www-data    0 Jun  8 19:00 oauth.log
```

I created the oauth.log file because it wasn't created at all. and it's still empty despite debug is on. So something is not working as it should.

2024-06-10 21:20 UTC, EdouardVanbelle commented
`oauth_config_uri` works only if you enabled the cache, which means ensuring:
```php
$config['oauth_cache'] = 'db';
$config['oauth_cache_ttl'] = '1d';
```
could you confirm you enabled it ?

if config uri does not work, you should have the reason  your `errors.log` (errors are kept in default errors.log)
something like: 
```Error fetching {$config_uri} : ...```

2024-06-11 06:41 UTC, oculos commented
This is my configuration: 

```
$config['oauth_provider'] = 'generic';
$config['oauth_provider_name'] = 'mydomain SSO';
$config['oauth_client_id'] = 'roundcube';
$config['oauth_client_secret'] = 'somesecret';
$config['oauth_auth_uri'] = 'https://auth.mydomain.eu/realms/mydomain/protocol/openid-connect/auth';
$config['oauth_token_uri'] = 'https://auth.mydomain.eu/realms/mydomain/protocol/openid-connect/token';
$config['oauth_identity_uri'] = 'https://auth.mydomain.eu/realms/mydomain/protocol/openid-connect/userinfo';
$config['oauth_scope'] = 'Roundcube_email openid';
$config['oauth_config_uri'] = 'https://auth.mydomain.eu/realms/mydomain/.well-known/openid-configuration';
$config['oauth_logout_uri'] = 'https://auth.mydomain.eu/realms/mydomain/protocol/openid-connect/logout';
$config['oauth_cache'] = 'db';
$config['oauth_debug'] = true;
$config['oauth_verify_peer'] = true;
$config['oauth_cache_ttl'] = '8h';
$config['oauth_identity_fields'] = ['postfixMailAddress'];
$config['oauth_login_redirect'] = true;
```

If I comment out `$config['oauth_token_uri'] = 'https://auth.mydomain.eu/realms/mydomain/protocol/openid-connect/token';`, I don't get pass the Roundcube login window with the login button.

Absolutely no new errors on `errors.log` when doing so.

2024-06-12 22:21 UTC, EdouardVanbelle commented
@oculos even if you comment out `oauth_token_uri`and provided the `oauth_config_uri` the  *discover()* method should grab it and explain any error in errors.log

Could you let met know which commit you are working on ?  so I could check to reproduce
I just need the hash:
```
git rev-parse --short HEAD
```

(feature is right now only available on master's branch which is still in development )

2024-06-13 06:06 UTC, oculos commented
Ohhh now I see. I mistakenly thought this was already added to the package that is publicly available (1.6.7). You see, I don’t install from the repo, I just download the package from Roundcube’s website. 
so sorry for wasting your time @EdouardVanbelle

2024-06-13 16:50 UTC, EdouardVanbelle commented
No worries @oculos, at least I provided a sample of use ;)