OAuth improvements (+ add user_create hook)
roundcube/roundcubemail pull request #9274
Opened 2023-12-17 21:50 UTC by EdouardVanbelle

Dear team, please find OAuth improvements

 * Core: Improv.: can specify an array on *_auth_type, lib will elect the best auth type according server's capabilities
 * OAuth: Refact.: migrate login flow into hooks (more evolutive code and less dependency to core code)
 * OAuth: Fix: logger prefix (include prefix duging login phase)
 * OAuth: Feat: add user_create hook (map OIDC claims when creating a new user)
 * OAuth: Lean: prepare OAUTHBEARER or XOAUTH2 in Sieve, SMTP, IMAP
     
This pull request also prepare the support of OAUTHBEARER and can already be merged, I will add OAUTHBEARER once:
 - pear Net_SMTP https://github.com/pear/Net_SMTP/pull/79 is accepted + included in a new release
 - pear Net_Sieve will have a new release (thank you @alecpl for the merge of https://github.com/pear/Net_Sieve/pull/10 )
 
 Many thanks for your time

2023-12-18 01:26 UTC, Neustradamus commented
@EdouardVanbelle: Excellent!

2023-12-18 23:58 UTC, EdouardVanbelle commented
Hello I also have another commit that bring the PKCE support (security improvement)
more details: https://datatracker.ietf.org/doc/html/rfc7636

the pending change is here: https://github.com/EdouardVanbelle/roundcubemail/compare/feat/hooks-and-oauth...EdouardVanbelle:roundcubemail:feat/oauth-pkce?expand=1

Let me know it you want I add it in this PR

This will cover this request: https://github.com/roundcube/roundcubemail/issues/8757

2023-12-20 21:38 UTC, EdouardVanbelle commented
Hello, I also implemented the use of the `nonce`, which is a security complement to `PKCE`
will be pushed on another request : https://github.com/EdouardVanbelle/roundcubemail/compare/feat/hooks-and-oauth...EdouardVanbelle:roundcubemail:feat/oauth-pkce?expand=1 )

2023-12-23 17:01 UTC, alecpl commented
- the smaller PRs are better, I'd prefer everything auth_type related in a separate PR
- regarding auth_type, I thought it would be better to implement method auto-selection in Net_Sieve and Net_SMTP. I.e. I'd make "OAUTH" type label, when set, these packages would use "OAUTHBEARER", and if not available "XOAUTH2". Setting type as an array looks needlessly overcomplicated.

2023-12-23 20:22 UTC, EdouardVanbelle commented
Hello I am going to split PR per features

Regarding OAUTH in libraries, I took the option that these libraries are low level
I also opt for an array, I thought it was more evolutive, seems that I took the wrong decision
I will check deeper according your suggestions ;-)

2023-12-23 21:20 UTC, EdouardVanbelle commented
Here is the point @alecpl 

This PR is now related to code refactorization to remove dependencies in core code with Oauth class and maximise use of hooks (better evolutivity + `program/actions/login/oauth.php` part is 95% similar to `index.php > login`'s section)
Once validated I will send a  PR per features:
* oauth: user_create  (code ready)
* oauth: pkce  (security improvement) (code ready)
* oauth: nonce (security improvement) (code ready)

While waiting approval I will step back on XOAUTH2/OAUTHBEARER routing/decision that fit your suggestions

Happy end of year celebrations

2023-12-25 09:25 UTC, alecpl requested changes

2023-12-25 09:25 UTC, alecpl commented on program/include/rcmail_oauth.php
> +    /** @var array */
`?array`, and the description should be inside /** */ here and below

2023-12-25 09:25 UTC, alecpl commented on program/include/rcmail_oauth.php
> +        $this->rcmail->config->set('login_password_maxlen', strlen($this->login_phase['authorization']));
You can use shorter `$options['pass']` here.

2023-12-25 18:05 UTC, EdouardVanbelle commented on program/include/rcmail_oauth.php
> +    /** @var array */
ok for the one line comment
not understood for `?array` ?

2023-12-25 18:09 UTC, EdouardVanbelle commented on program/include/rcmail_oauth.php
> +    /** @var array */
ok seems to be a way to mention a hash map/array, seen in `program/lib/Roundcube/rcube_addressbook.php`

2023-12-25 18:17 UTC, alecpl commented on program/include/rcmail_oauth.php
> +    /** @var array */
`?array` means `array|null`.

2023-12-25 23:23 UTC, EdouardVanbelle commented on program/include/rcmail_oauth.php
> +    /** @var array */
Thank you for clarification, I applied correction `?array` to `$login_phase`

2023-12-25 23:48 UTC, EdouardVanbelle commented
Hello @alecpl I added this PR: https://github.com/roundcube/roundcubemail/pull/9284 in order to fix coding style not related to this change

2023-12-26 08:07 UTC, merged

2023-12-26 08:18 UTC, Neustradamus commented
@EdouardVanbelle: Good job!

Can you look for SCRAM hashes security feature too?

2023-12-26 09:00 UTC, EdouardVanbelle commented
Hello @Neustradamus , why not, seems my dovecot supports SCRAM, will check it when I handle time to do it

2023-12-26 12:39 UTC, Neustradamus commented
@EdouardVanbelle: Nice, thanks in advance :)

About Dovecot, please note that @stephanbosch is on SCRAM-SHA-1-PLUS/SCRAM-SHA-256-PLUS: https://github.com/dovecot/core/compare/main...stephanbosch:dovecot-core:sasl-scram-plus

He has already done several years ago several lines about SCRAM: https://github.com/search?q=repo%3Adovecot%2Fcore+scram&type=commits&s=author-date&o=desc

For -PLUS variants, there are 3 possibilities:
- tls-unique for TLS =< 1.2
- tls-server-end-point
- tls-exporter for TLS = 1.3

About Cyrus-SASL:
- https://github.com/search?q=repo%3Acyrusimap%2Fcyrus-sasl+scram&type=code

About Cyrus-Imapd:
- https://github.com/search?q=repo%3Acyrusimap%2Fcyrus-imapd+scram&type=code
- @GuidoKiener works on it: https://github.com/cyrusimap/cyrus-imapd/pull/4772