oauth: feat: use OIDC claims on user creation
roundcube/roundcubemail pull request #9286
Opened 2023-12-26 09:28 UTC by EdouardVanbelle

Hello please find the user_create hook that uses the OIDC's identify when creating a new user

2023-12-26 10:11 UTC, alecpl requested changes

2023-12-26 10:11 UTC, alecpl commented on program/include/rcmail_oauth.php
> +                if (isset($identity[$oidc_claim]) && $identity[$oidc_claim] !== null) {
Check for null is redundant. Maybe we should just use `!empty()` or check whether it's a non-empty string?

2023-12-26 10:11 UTC, alecpl commented on program/include/rcmail_oauth.php
> +            if (!is_array($oidc_claims)) {
I usually do just a casting to array in such cases.

2023-12-26 10:11 UTC, alecpl commented on config/defaults.inc.php
> +$config['oauth_user_create_map'] = null;
Set the default array here instead of null.

2023-12-26 10:11 UTC, alecpl commented on program/include/rcmail_oauth.php
> +            $this->log_debug("identity not found, was the scope 'openid' defined ?");
no space before `?`.

2023-12-26 10:11 UTC, alecpl commented on program/include/rcmail_oauth.php
> +        $this->log_debug("setup account creation of user:%s host:%s with user_name:%s user_email:%s lang:%s",
Maybe it would be better to just log the items we got from the token identity.

2023-12-26 10:11 UTC, alecpl commented on program/include/rcmail_oauth.php
> +                    $data[$rc_key] = $identity[$oidc_claim];
Maybe we should validate the values coming from outside?

2023-12-26 17:48 UTC, EdouardVanbelle commented on program/include/rcmail_oauth.php
> +            if (!is_array($oidc_claims)) {
good to know, thanks

2023-12-26 18:32 UTC, EdouardVanbelle commented on program/include/rcmail_oauth.php
> +            $this->log_debug("identity not found, was the scope 'openid' defined ?");
just a french reflex :)

2023-12-26 21:22 UTC, EdouardVanbelle commented on program/include/rcmail_oauth.php
> +                if (isset($identity[$oidc_claim]) && $identity[$oidc_claim] !== null) {
I opted for non empty string

2023-12-26 21:26 UTC, EdouardVanbelle commented on program/include/rcmail_oauth.php
> +                    $data[$rc_key] = $identity[$oidc_claim];
Good catch, here what I did:
1. ensure config setup only allowed keys (user & host are for example forbidden)
2. normalizing user_email & language, then I check validity

I also added tests

2023-12-27 00:57 UTC, Neustradamus commented
@EdouardVanbelle: Nice, good job!

Linked to:
- https://github.com/roundcube/roundcubemail/pull/9274
- https://github.com/roundcube/roundcubemail/pull/9286
- https://github.com/roundcube/roundcubemail/pull/9287
- https://github.com/roundcube/roundcubemail/pull/9288
- https://github.com/roundcube/roundcubemail/pull/9289
- https://github.com/pear/Net_SMTP/pull/79
- https://github.com/pear/Net_Sieve/pull/10
- https://github.com/pear/Net_Sieve/pull/11

2023-12-27 08:23 UTC, alecpl commented
@Neustradamus Please, stop adding this references. It's misleading, not everything is related.

2023-12-28 18:05 UTC, EdouardVanbelle commented on program/include/rcmail_oauth.php
> +                    $data[$rc_key] = $identity[$oidc_claim];
I just changed the language check, the list_languages() was too strict

```diff
-                            // check that language is supported
-                            $languages = $this->rcmail->list_languages();
-                            if (!array_key_exists($value, $languages)) {
+                            // check that language is at the correct format
+                            if (!preg_match('/^[a-z]{2}(\_[A-Z]{2,})?$/', $value)) {
                                 rcube::raise_error([
```

2023-12-28 18:49 UTC, alecpl commented on program/include/rcmail_oauth.php
> +                            if (!preg_match('/^[a-z]{2}(\_[A-Z]{2,})?$/', $value)) {
That's not going to work with languages like "ast" or "es_419"

2023-12-28 21:44 UTC, EdouardVanbelle commented on program/include/rcmail_oauth.php
> +                            if (!preg_match('/^[a-z]{2}(\_[A-Z]{2,})?$/', $value)) {
What about this simplification?

```php
   // check that language is in the correct format (over simplification of RFC5646)
   if (!preg_match('/^[a-zA-Z]{2,8}(\_[a-zA-Z0-9]{1,8})*$/', $value)) {
  ...
```

Which already sanitize data and ensure you are not going to have temptative hacks like `$language="../../../password"` or similar 

What is the requirement on the user's property `language` 
- does it need to be the wished language from the customer? (allow language to be added lately) 
- or does it need to be a truly and currently supported language by roundcube?

If it as to be a supported language, the best option I see is to change `rcube->language_prop()` from `protected` to `public` and use it in this hook

What do you think ?

2023-12-29 07:16 UTC, alecpl commented on program/include/rcmail_oauth.php
> +                            if (!preg_match('/^[a-z]{2}(\_[A-Z]{2,})?$/', $value)) {
In another place we're using `/^[a-zA-Z0-9_-]+$/`, but I'd add a length limit, lets say 8, and it will be fine.

2023-12-29 09:06 UTC, EdouardVanbelle commented on program/include/rcmail_oauth.php
> +                            if (!preg_match('/^[a-z]{2}(\_[A-Z]{2,})?$/', $value)) {
done

please note, I saw that `rcube->language_prop()` is capturing browser's accepted language via
```php
            if (preg_match('/^([a-z]+)[_-]([a-z]+)$/i', $lang, $m))
```            

I added this: https://github.com/roundcube/roundcubemail/pull/9292

2023-12-29 18:10 UTC, merged