oauth: feat: add support of PKCE
roundcube/roundcubemail pull request #9287
Opened 2023-12-26 09:59 UTC by EdouardVanbelle

Hello please find the PKCE implementation (RFC 7636)

- by default it is enabled, if server do not implement it, PKCE extra parameters will be ignored (as requested by RFC)
- I did not implemented plain as requested as we can directly support `S256` hash method
- I used a hash array to prepare future hahses (even if RFC specifies only `S256` right now) 

This covers this request: https://github.com/roundcube/roundcubemail/issues/8757

2023-12-26 10:26 UTC, alecpl requested changes

2023-12-26 10:26 UTC, alecpl commented on config/defaults.inc.php
> +$config['oauth_pkce'] = null;
Set the default here.

2023-12-26 10:26 UTC, alecpl commented on program/include/rcmail_oauth.php
> +        if ($this->options['pkce'] === true) {
Handling `true` is not needed.

2023-12-26 10:26 UTC, alecpl commented on program/include/rcmail_oauth.php
> +        $this->log_debug("requesting authorization code via a redirect to %s with scope='%s' and pkce method=%s",
I'm just thinking maybe logging the full url instead would be better.

2023-12-26 17:07 UTC, EdouardVanbelle commented on program/include/rcmail_oauth.php
> +        if ($this->options['pkce'] === true) {
Yes, I am always very permissive for admin/users, I convert 'true' to the default value
Removing it

2023-12-26 17:18 UTC, EdouardVanbelle commented on program/include/rcmail_oauth.php
> +        $this->log_debug("requesting authorization code via a redirect to %s with scope='%s' and pkce method=%s",
I did it to avoid leak of sensitive data like the `nonce` in other pull request

2023-12-27 00:58 UTC, Neustradamus commented
@EdouardVanbelle: Nice, good job!

Linked to:
- https://github.com/roundcube/roundcubemail/pull/9274
- https://github.com/roundcube/roundcubemail/pull/9286
- https://github.com/roundcube/roundcubemail/pull/9287
- https://github.com/roundcube/roundcubemail/pull/9288
- https://github.com/roundcube/roundcubemail/pull/9289
- https://github.com/pear/Net_SMTP/pull/79
- https://github.com/pear/Net_Sieve/pull/10
- https://github.com/pear/Net_Sieve/pull/11

2023-12-27 08:28 UTC, alecpl requested changes

2023-12-27 08:28 UTC, alecpl commented on program/include/rcmail_oauth.php
> +    public static function base64url_encode($payload)
I think both these methods should be not public.

2023-12-27 08:28 UTC, alecpl commented on program/include/rcmail_oauth.php
> +        $_SESSION['oauth_state'] = rcube_utils::random_bytes(32);
Does it have to be 32. Is it in some standard?

2023-12-27 08:47 UTC, EdouardVanbelle commented on program/include/rcmail_oauth.php
> +    public static function base64url_encode($payload)
Your right I kept the same login as the initial version which was public, changing it to protected

2023-12-27 08:48 UTC, EdouardVanbelle commented on program/include/rcmail_oauth.php
> +        $_SESSION['oauth_state'] = rcube_utils::random_bytes(32);
juste my paranoid reflex

2023-12-27 09:57 UTC, merged

2023-12-27 12:44 UTC, EdouardVanbelle commented
Thank you !