Don't render quota if it's unlimited
roundcube/roundcubemail pull request #9310
Opened 2024-01-18 08:38 UTC by pabzm

In case an accounts's quota is zero and the config option `quota_zero_as_unlimited` is true, then the account has no quota and should not be shown a meaningless (or even wrong) quota-display.

This introduces a new function to avoid repeating identical code in two places.

If a template doesn't check for the env-flag it still can render quota details.

This PR closes #8994.

One question and two notes:
* This doesn't include a Changelog-entry yet – should I add one or do you rather compile those yourselves?
* Also I didn't touch the templates, so the `.footer`-element of the column remains even if it is blank (because the `if`-clauses in the templates are inside that element) – I'm not sure if that needs to stay like that but didn't feel comfortable changing the template without knowing why it was written like this. And I think it looks okay, event with an empty element. If you want the footer gone, please let me know.
* And since there's no test case for this feature I didn't change any. Adding a fresh one is a little out of my time budget currently, because I'd need to dive into the setup first.

2024-01-18 08:46 UTC, pabzm commented
Hm, I'll have a look at those tests

2024-01-18 09:07 UTC, pabzm commented
The remaining failures from the CI are not related to my changes, as far as I can see. Is there anything I can do about them?

2024-01-23 09:36 UTC, pabzm commented
@miaulalala, @ChristophWurst I only now realized that I didn't yet notify you of this pull request, sorry for that! I can't assign you as reviewers, though. Would you have a look?

2024-01-24 19:13 UTC, miaulalala requested changes, later dismissed

2024-01-24 19:13 UTC, miaulalala commented on program/include/rcmail_action.php
> +        $show_quota = is_array($quota) && !($quota['total'] === 0 && $zero_as_unlimited);
It's not working for me since the $quota array is empty in my case. 

Something similar to this could work.

```suggestion
        $show_quota = empty($quota) || (is_array($quota) && !($quota['total'] === 0 && $zero_as_unlimited);
```

2024-01-24 19:13 UTC, miaulalala commented on program/include/rcmail_action.php
> +        $zero_as_unlimited = (bool) $rcmail->config->get('quota_zero_as_unlimited');
since you have a config param here, you could check that first and early return if that config param is set to false.

```suggestion
        $zero_as_unlimited = (bool) $rcmail->config->get('quota_zero_as_unlimited');
        
        if($zero_as_unlimited === false) {
        	$rcmail->output->set_env('quota', true);
        	return;
        }
```

2024-01-25 09:32 UTC, pabzm commented on program/include/rcmail_action.php
> +        $show_quota = is_array($quota) && !($quota['total'] === 0 && $zero_as_unlimited);
I had considered that we could also skip displaying the quota-element if there's no quota data to show. That goes a little beyond the original issue's content but seemed right to me, because currently in this case (empty quota array) the element is shown as if no quota were used at all and its title is "unknown", which to me feels like a rather bad fallback.

(At least that's the case in my setup. Is it the same in yours?)

I'll happily use your suggestion if you still think it's right, just wanted to explain my change.

2024-01-25 09:50 UTC, pabzm commented on program/include/rcmail_action.php
> +        $zero_as_unlimited = (bool) $rcmail->config->get('quota_zero_as_unlimited');
Thank you for the hint! I added a second early check, which catches the case that the server doesn't event support quotas.

2024-01-25 09:57 UTC, miaulalala commented on program/include/rcmail_action.php
> +        $show_quota = is_array($quota) && !($quota['total'] === 0 && $zero_as_unlimited);
It's empty for me - it still works and shows "unlimited".

2024-01-25 09:59 UTC, miaulalala commented
Isn't the config option a bit misleading? If I have an unlimited quota and explicitly set that option, imho the intention is to show "unlimited" in the quota display. Or am I misunderstanding this?

2024-01-25 10:14 UTC, miaulalala commented
> I think the config option is correct, because it only specifies that a quota of zero should mean unlimited.
> 
> But the consequence to then not show the element surprised me, too (only didn't dare to question the original decision).
> 
> Maybe showing the quota-icon and the text "unlimited" (or ♾️) instead of the bar and percentage would be an option?

sounds like a good idea. So cases are:

Quota is not supported - don't show anything

Quota is supported
- Unlimited with config option true - show infinity sign instead of bar / %
- Unlimited with config option false - don't show anything
- Not unlimited - keep current display

2024-01-25 10:37 UTC, pabzm commented
> Unlimited with config option true - show infinity sign instead of bar / %
> Unlimited with config option false - don't show anything

Why not show the infinity sign in all cases of unlimited quota?

Also, maybe there's still a misunderstanding: I think the config option tells that `quota["total"] === 0` should mean "unlimited", not "zero byte allowed". So it doesn't govern what to do with the info "unlimited" but only how to determine it in a special case.

Thus I'd suggest these cases:

- Quota is not supported - don't show anything
- Quota is unlimited - show infinity sign instead of bar / %
- Quota is not unlimited - keep current display

What do you think?

2024-01-25 10:40 UTC, pabzm commented
Note to self: an empty quota-list and thus empty `$quota`-array is not an error but means "all mailboxes unlimited" (according to [RFC 2087](https://datatracker.ietf.org/doc/html/rfc2087.html#section-5)).

2024-01-25 11:02 UTC, pabzm commented
> Also, maybe there's still a misunderstanding: I think the config option tells that $quota["total"] === 0 should mean "unlimited", not "zero byte allowed". So it doesn't govern what to do with the info "unlimited" but only how to determine it in a special case.

No, you're right: it does more than that, [it also governs if unlimited quota is titled as "unlimited" or "unknown"](https://github.com/roundcube/roundcubemail/blob/eeac27ea81cc27abbab88314c6dd5dc3440d38c7/program/include/rcmail_action.php#L249-L250), regardless of how the unlimited quota is determined. In that way it's actually also misleading, because you need to set it to get the title "unlimited" even if your IMAP-server doesn't send a quota-value of zero to mean "unlimited".

2024-01-25 11:04 UTC, pabzm commented
But the suggested changes would (silently) fix that misleading usage without hurting nor breaking anything, I think.

2024-01-25 11:18 UTC, pabzm commented
The coding style check fails doe to code we might throw away in the next iteration, and the failing test is unrelated (AFAICS), so I'll deal with those later if they still fail.

2024-01-25 11:54 UTC, miaulalala commented
> > Unlimited with config option true - show infinity sign instead of bar / %
> > Unlimited with config option false - don't show anything
> 
> Why not show the infinity sign in all cases of unlimited quota?
> 
> Also, maybe there's still a misunderstanding: I think the config option tells that `$quota["total"] === 0` should mean "unlimited", not "zero byte allowed". So it doesn't govern what to do with the info "unlimited" but only how to determine it in a special case.
> 
> Thus I'd suggest these cases:
> 
> * Quota is not supported - don't show anything
> * Quota is unlimited - show infinity sign instead of bar / %
> * Quota is not unlimited - keep current display
> 
> What do you think?

makes sense!

2024-01-25 12:14 UTC, alecpl commented
I don't like the idea of "infinity sign". Also, while I see  an unknown quota indication might makes some sense, I think that we should just hide the widget whenever the quota is unsupported, unknown or unlimited.

2024-01-25 13:22 UTC, pabzm commented
@alecpl I think it's helpful to let people know about their quota, also if it is unlimited. Not showing it looks more like a broken feature to me, especially if I think about users that might work with different accounts or servers, and then sometimes get to see the information and sometimes it's missing.

We could also use the translation of "unlimited" (as it currently is used for the `title`-attribute) instead of the infinity sign?

2024-01-26 12:24 UTC, pabzm commented
So now if quota is unsupported, unlimited or "unknown" it won't get shown.

This drops using the config option `quota_zero_as_unlimited`, because unlimited and "unknown" are handled identically.

As far as I can tell the Changelog is written by @alecpl, so I didn't touch it. Please let me know if you want a change there.

2024-01-26 12:27 UTC, pabzm commented
I could also squash the branch to get rid of the previous commits if you're ok with that.

2024-01-26 12:59 UTC, alecpl commented
Zero is not unknown, but I'm for dropping the option, unless someone has a good use case for quota=0.

2024-01-26 17:14 UTC, miaulalala approved these changes

2024-01-29 16:24 UTC, pabzm commented
Is there anything left for me to do in this PR?

(I don't mean to push, just to avoid misunderstandings.)

2024-01-29 17:30 UTC, miaulalala commented
> Is there anything left for me to do in this PR?
> 
> (I don't mean to push, just to avoid misunderstandings.)
Not from my side.

@alecpl , anything from your side?

2024-02-11 17:39 UTC, alecpl commented
- The diff conflict needs to be resolved
- This change has a small performance impact (extra `GETQUOTAROOT` commands). An alternative approach could be to make the quota element hidden on page load and only when set_quota command is being send to the client-side it could be shown (if needed).

2024-02-14 14:53 UTC, pabzm commented
> An alternative approach could be to make the quota element hidden on page load

Do you mean hidden by JavaScript, or by markup in the template?

The latter would be more robust but requires cooperation of the template, so admins providing different skins would need to change code, I guess – that might be a problem?

2024-02-14 17:28 UTC, alecpl commented
Yeah, from the template or skin css (I'm not sure which one is better), and then un-hidden in `setquota` event handler that skins use. So, it would require some changes in skins anyway. Also hiding the parent element would make sens too, this part definitely should be done in the skin itself only.

2024-02-21 13:09 UTC, pabzm commented
I made a new PR to keep things clean: https://github.com/roundcube/roundcubemail/pull/9366

2024-06-03 12:30 UTC, pabzm commented
Superseded by #9366

2024-06-03 12:30 UTC, closed without merging