Contact import improvements
roundcube/roundcubemail pull request #9431
Opened 2024-05-01 19:01 UTC by johndoh

For #9419

Some of the mappings in the current code work (pass the tests) but the result is different to what you get if you create the same contact manually through the UI and then export it as a vCard, for example Roundcube uses `phone:mobile` not `phone:cell` and there is no `email:pref` field. I have changed the mapping so it matches the fields in the UI. I added some more aliases `rcube_vcard` to show existing vCards with mismatched fields nicely.

I have removed the subtype `other` from the IM field because that does not exist in `rcube_vcard` which means if when you hit save in the UI the value simply disappears, it’s not saved.

I have removed the variable `rcube_csv2vcard::$label_map` because it’s a duplicate of contents of `/program/localization/en_US/csv2vcard.inc`and just a bit confusing currently `/program/localization/en_US/csv2vcard.inc` is not used by the code and this PR changes that.

I have another reason for wanting to use `/program/localization/en_US/csv2vcard.inc` over `rcube_csv2vcard::$label_map` and if this PR gets merged then I will propose 1 additional change which will remove the `rcube_csv2vcard::$csv2vcard_map` variable and simplify the mapping process by storing both the source and destination for the map in `/program/localization/en_US/csv2vcard.inc` and allowing multiple sources (including multiple languages) for the same destination. This is a slightly larger and may be more controversial change hence the separate PR.

2024-06-01 07:20 UTC, alecpl requested changes

2024-06-01 07:20 UTC, alecpl commented on program/actions/contacts/import.php
> +        asort($available_fields);
We need should use SORT_LOCALE_STRING flag.

2024-06-01 07:20 UTC, alecpl commented on program/actions/contacts/import.php
> +        $available_fields['birthday-y'] = $rcmail->gettext('birth_year');
Maybe these extra fields definition should be stored in rcube_csv2vcard class.

2024-06-01 07:20 UTC, alecpl commented on program/lib/Roundcube/rcube_csv2vcard.php
> +        'im_other' => 'im:other',
Didn't you remove that field?

2024-06-01 07:20 UTC, alecpl commented on program/lib/Roundcube/rcube_vcard.php
> +        'HOOME,FAX' => 'homefax',
A typo.

2024-06-01 07:20 UTC, alecpl commented on program/localization/en_US/labels.inc
> +$labels['contactaddressfieldtype'] = '$subtype $field';
I'm not sure these two need to be here at all.

2024-06-01 09:05 UTC, johndoh commented on program/lib/Roundcube/rcube_vcard.php
> +        'HOOME,FAX' => 'homefax',
are you suggesting `work,cell` should map to `mobile`? there is no `workmobile` field type.

2024-06-01 09:08 UTC, johndoh commented on program/lib/Roundcube/rcube_csv2vcard.php
> +        'im_other' => 'im:other',
I have not removed anything

2024-06-01 09:14 UTC, johndoh commented on program/localization/en_US/labels.inc
> +$labels['contactaddressfieldtype'] = '$subtype $field';
In the contact UI the fields are displayed in different sections e.g. home, work, other but on the import screen where there is only a simple select box i needed way to differentiate the types of field. I don't know if its written as "phone work" in all languages so to be safe i included the format in the localization file. There are 2 because for most fields like written like "phone home" to group all the phone fields together in the list but for address fields its like "home city" so the parts of the address are together.

2024-06-01 10:27 UTC, alecpl requested changes

2024-06-01 10:27 UTC, alecpl commented on program/lib/Roundcube/rcube_csv2vcard.php
> +        'im_other' => 'im:other',
I was referring to im:other that you removed in program/actions/contacts/index.php

2024-06-01 10:27 UTC, alecpl commented on program/lib/Roundcube/rcube_vcard.php
> +        'HOOME,FAX' => 'homefax',
A typo in "HOOME".

2024-06-01 10:27 UTC, alecpl commented on program/localization/en_US/labels.inc
> +$labels['contactaddressfieldtype'] = '$subtype $field';
I think it should/could be "city - home" "phone - home" (or "city (home)", "phone (home)"). Using localization for this is wrong and will not work for many languages.

2024-06-02 08:51 UTC, johndoh commented on program/actions/contacts/import.php
> +        $available_fields['birthday-y'] = $rcmail->gettext('birth_year');
created new rcube_csv2vcard::list_fields()

2024-06-16 10:55 UTC, johndoh commented
I moved the `list_fields` function back to `rcmail_action_contacts_import` because it relies on the contact list from its parent class `rcmail_action_contacts`. I think its the best place for it.

Also I completed the second part of my suggestion to remove the hard coded mapping information entirely and use 1 to define the source and destination.

2024-07-21 11:22 UTC, alecpl requested changes

2024-07-21 11:22 UTC, alecpl commented on program/actions/contacts/index.php
> +            'subtypes' => ['aim', 'icq', 'msn', 'yahoo', 'jabber', 'skype'],
Why 'other' is removed here?

2024-07-21 11:22 UTC, alecpl commented on program/localization/de_CH/csv2vcard.inc
> +$map['anniversary'][] = "Jahrestag";
I don't like this change. We should keep this file syntax simple.

2024-07-21 12:22 UTC, johndoh commented on program/actions/contacts/index.php
> +            'subtypes' => ['aim', 'icq', 'msn', 'yahoo', 'jabber', 'skype'],
Because it's not supported by the rest of the code. It's not included in the vCard, so once you hit save the value is lost.

2024-07-21 12:26 UTC, johndoh commented on program/localization/de_CH/csv2vcard.inc
> +$map['anniversary'][] = "Jahrestag";
What is not simple about the syntax? This way, the mapping process is clearer. There is only one map of CSV field to vCard field rather than the CSV to internal ID, then a hard coded map of internl ID to vCard used currebtly. It also adds support variations of field names in the CSV file.

2024-07-21 12:45 UTC, alecpl commented on program/localization/de_CH/csv2vcard.inc
> +$map['anniversary'][] = "Jahrestag";
`$map['anniversary'][]` is not simple ;)

2024-08-25 07:06 UTC, johndoh commented on program/localization/de_CH/csv2vcard.inc
> +$map['anniversary'][] = "Jahrestag";
The reason for the nested array is to allow multiple labels to map to the same vCard field, e.g. currently the CSV labels `first` and `given_name` both map to vCard field `firstname`. Currently this is done via the hard coded `rcube_csv2vcard::$csv2vcard_map`. For me this is not simple. Adding a new field into the map means a change in 2 files, you have to know the hard coded map is there, there is no info about it in `csv2vcard.inc`. Using a nested array may not be simple but for me it is simpler than the current approach as it means there is only 1 place to change when adding a new field.

2024-11-20 07:46 UTC, pabzm commented on program/localization/de_CH/csv2vcard.inc
> +$map['anniversary'][] = "Jahrestag";
I understand your approach but also understand Alec's concern and share the latter here. To me, `csv2vcard.inc` is a config file, and so the priority should be readability for humans. Understanding the syntax is one thing (which might be hard for non-PHP-developers), another thing I don't understand without intimate knowledge of the code is why e.g. `email:other` gets three values:

```
$map['email:other'][] = "E-mail Address";
$map['email:other'][] = "E-mail 2 Address";
$map['email:other'][] = "E-mail 3 Address";
```

Can we find a way to specify the mapping while keeping your approach (which I do like!) to de-duplicate and strip indirection?

2025-09-24 06:21 UTC, johndoh commented
@pabzm any chance this could be part of 1.7?

2025-09-24 12:50 UTC, pabzm commented
From my point of view, yes. I don't really like the syntax in the `csv2vcard.inc`-files, but I'm happy about the cleanup and those files don't change often, so it's not a big problem and shouldn't block us, I think.

@alecpl What do you think about this?

2025-09-25 15:19 UTC, johndoh commented
>From my point of view, yes. I don't really like the syntax in the csv2vcard.inc-files, but I'm happy about the cleanup and those files don't change often, so it's not a big problem and shouldn't block us, I think.

I'll have to refresh my memory a bit but may be i could find a way to flip it round so in `csv2vcard.inc` its like
```php
$map['<CSV File Name>'] = "<vCard Field>";
$map['E-mail Address'] = "email:other";
$map['E-mail 2 Address'] = "email:other";
$map['E-mail 3 Address'] = "email:other";
```
would that be more acceptable?

2025-10-01 07:51 UTC, pabzm commented
Much nicer, thank you! Can we make the format even more close by swapping keys and values in the inc-files, and run `array_flip()` on them after reading?

2025-10-01 08:11 UTC, johndoh commented
I put them this way round because multiple CSV fields are mapped to the same vCard field so, I think, its either:
```php
$map['email:other'][] = "E-mail Address";
$map['email:other'][] = "E-mail 2 Address";
$map['email:other'][] = "E-mail 3 Address";
```
or
```php
$map['E-mail Address'] = 'email:other';
$map['E-mail 2 Address'] = 'email:other';
$map['E-mail 3 Address'] = 'email:other';
```

2025-10-01 08:18 UTC, pabzm commented
Oh, alright! Then I prefer the second and current way.

Thank you again!

2025-10-01 08:18 UTC, pabzm approved these changes

2025-10-08 11:36 UTC, alecpl approved these changes

2025-10-08 11:36 UTC, merged