Add managesieve_host array handler
roundcube/roundcubemail pull request #9447
Opened 2024-05-10 09:15 UTC by gerbert

To use different sieve hosts for different domains, the rcube_sieve_engine.php was updated and the connect() function was extended to handle managesive_host config option being configured as an array.
One use case scenario now could be to use the managesieve_host option the following way:

```
$config['managesieve_host'] = array(
    'some.domain' => 'localhost',
    'another.doman' => 'tls://yet.another.domain,
);
```
Where `some.domain` should match corresponding `username_domain` entry.

2024-05-13 07:54 UTC, pabzm commented
Thank you for this contribution! 

I like it and think it has a good chance to be merged, but please change the code comment to tell about hostnames to avoid misunderstanding.

(You may ignore the CI error about the JS coding style.)

2024-05-13 12:18 UTC, gerbert commented
> Thank you for this contribution!
> 
> I like it and think it has a good chance to be merged, but please change the code comment to tell about hostnames to avoid misunderstanding.
> 
> (You may ignore the CI error about the JS coding style.)

Hi! Do you mean, `// Extract the host name from the session`?

2024-05-13 12:46 UTC, pabzm commented on plugins/managesieve/config.inc.php.dist
> +// of domain (no prefix or port) and sieve server e.g. ['example.com' => 'sieve.example.net']
The code maps hostnames, not domainnames, please update this explanation. Also maybe include a note that the hostnames are ASCII-fied in case of IDN and must be specified accordingly to match?

(This comment didn't make it across the network earlier, sorry!)

2024-05-13 13:00 UTC, pabzm commented on plugins/managesieve/config.inc.php.dist
> +// of domain (no prefix or port) and sieve server e.g. ['example.com' => 'sieve.example.net']
The first one looks good!

If you change the second please include the option that `managesieve_host` still might contain a string.

2024-05-13 15:06 UTC, pabzm commented on plugins/managesieve/config.inc.php.dist
> +// of domain (no prefix or port) and sieve server e.g. ['example.com' => 'sieve.example.net']
Looks good to me, thank you very much!

2024-05-13 15:06 UTC, pabzm approved these changes

2024-05-14 09:45 UTC, pabzm commented
Please rebase this onto the latest `master`-branch to fix the CI.

2024-05-14 11:32 UTC, gerbert commented
> Please rebase this onto the latest `master`-branch to fix the CI.

done!

2024-05-16 14:34 UTC, alecpl commented on plugins/managesieve/lib/Roundcube/rcube_sieve_engine.php
> +                return rcmail::ERROR_INVALID_HOST;
`rcube_sieve::ERROR_CONNECTION` would be better here.

2024-05-16 15:11 UTC, gerbert commented on plugins/managesieve/lib/Roundcube/rcube_sieve_engine.php
> +                return rcmail::ERROR_INVALID_HOST;
Done.

2024-05-16 16:40 UTC, alecpl requested changes
Rebase, please and we're good to go.

2024-05-16 16:40 UTC, alecpl commented on plugins/managesieve/lib/Roundcube/rcube_sieve_engine.php
> +        // $config['managesieve_host'] parameter now can be configured in two ways:
Add an empty line here, please.

2024-05-16 16:40 UTC, alecpl commented on plugins/managesieve/lib/Roundcube/rcube_sieve_engine.php
>          $host = rcube_utils::parse_host($host);
Add an empty line here, please.

2024-05-16 17:42 UTC, gerbert commented on plugins/managesieve/lib/Roundcube/rcube_sieve_engine.php
> +        // $config['managesieve_host'] parameter now can be configured in two ways:
Done

2024-05-16 17:42 UTC, gerbert commented on plugins/managesieve/lib/Roundcube/rcube_sieve_engine.php
>          $host = rcube_utils::parse_host($host);
Done

2024-05-16 17:49 UTC, gerbert commented
> Rebase, please and we're good to go.

Please check if the commentary about managesieve_host is ok. Because the master branch was updated as well and the code in the exact the same place changed a bit.

2024-05-17 11:11 UTC, pabzm commented
I'm still happy with this 👍

2024-05-17 11:11 UTC, pabzm approved these changes

2024-05-19 13:11 UTC, merged