Test message rendering
roundcube/roundcubemail pull request #9460
Opened 2024-05-21 15:29 UTC by pabzm

This adds an integration testing setup to check the rendering of individual emails. The idea is to grow this with a lot of "normal" and "interesting" messages, to have a solid base for fixing new rendering errors without breaking previous fixes (motivated by #9443). It would also help with possible refactoring.

Run ./tests/MessageRendering/run-tests.sh to run all tests in that directory.  They are ignored when running the main test suite (for now).

The messages are served by a dovecot container from the Maildir in
`tests/MessageRendering/src/maildir` and identified by their `Message-Id`. This way one can drop a raw email into there, and immediately write a test against it.

This is not yet built into the GitHub workflows, and also has only a few messages and tests, because before putting more work into this I'd like to have some feedback.

@roundcube/webmail-developers What do you think about?

2024-05-21 17:45 UTC, pabzm commented
Sorry, it took me a moment to wrestle with phpstan, the cs-fixer and windows filename problems. It's ready now and I won't force-push anymore.

2024-05-24 11:17 UTC, miaulalala approved these changes
Looks good!

2024-05-24 11:53 UTC, pabzm commented
Actually this conflicts with the work I did for #9465 (which only occured to me yesterday), so I'd not push this before that other topic was discussed.

2024-06-01 07:02 UTC, alecpl requested changes

2024-06-03 12:15 UTC, pabzm commented on tests/MessageRendering/MessageRenderingTestCase.php
> +    protected function run_and_get_html_output_domxpath(string $msg_id): \DOMXPath
Sorry for mixing styles. https://github.com/roundcube/roundcubemail/wiki/Dev-Guidelines#classes-functions-and-variables says: "No CamelCase", but the repo has some. Which way would you prefer?

2024-06-03 12:16 UTC, pabzm commented on tests/MessageRendering/bootstrap.php
> +<?php
I'd like to postpone the integration until it works as we want it, ok?

2024-06-03 12:20 UTC, pabzm commented on tests/MessageRendering/MessageRenderingTestCase.php
> +        $rcmail->login('test', 'pass', 'tls://localhost');
> n Browser tests we're using a standalone imap server from Greenmail. Maybe that would be better approach than dovecot

I'll have a look at it, thank you for the hint!

> That means you'd have to append the test messages if not in INBOX.

I'm not sure I understand: If using Greenmail I'd have to append the messages? Or if using other folders? 

Currently the code is only using the INBOX, because it focusses on the message's content rendering, not how listings are rendered. So then I don't need to append any messages, right?

2024-06-03 12:21 UTC, pabzm commented on tests/MessageRendering/MessageRenderingTestCase.php
> +        $mock_storage = $rcmail->storage = null;
Until we improve that, can we use this code as it is? As far as I can see it doesn't break other tests.

2024-06-03 12:22 UTC, alecpl commented on tests/MessageRendering/MessageRenderingTestCase.php
> +    protected function run_and_get_html_output_domxpath(string $msg_id): \DOMXPath
Camel-case here as this is a new class in tests.

2024-06-03 12:24 UTC, pabzm commented on tests/MessageRendering/src/maildir/cur/attachment-gh9443.eml
> +Message-Id: <XXXXXXXXXXXXX@mx01.lytzenitmail.dk>
I'll rename the folder but keep it in the subdirectory until this is ready for integration with the main test suite.

2024-06-04 09:02 UTC, pabzm commented on tests/MessageRendering/MessageRenderingTestCase.php
> +        $rcmail->login('test', 'pass', 'tls://localhost');
Thank you for the explanation!

Why do you think using Greenmail would be better? It is also "just" a standalone IMAP-Server, isn't it? Since we're not using Java, we cannot hook into it for our tests, as far as I understand.
With two standalone IMAP-Servers, wouldn't it be better to test against the one that is most used in live systems?

2024-06-04 09:03 UTC, pabzm commented on tests/MessageRendering/MessageRenderingTestCase.php
> +    protected function run_and_get_html_output_domxpath(string $msg_id): \DOMXPath
Ok. Do you want CameCase only in new tests or in all new code?

2024-06-04 09:08 UTC, alecpl commented on tests/MessageRendering/MessageRenderingTestCase.php
> +    protected function run_and_get_html_output_domxpath(string $msg_id): \DOMXPath
No necessarily in tests, but in utility classes like this for sure. I think we can do this in tests too, especially in new files where there's no old code in another style.

2024-06-04 09:12 UTC, alecpl commented on tests/MessageRendering/MessageRenderingTestCase.php
> +        $rcmail->login('test', 'pass', 'tls://localhost');
A developer should be able to easily run these tests on their PC. I think that using a self-contained file is better than a need to install dovecot in the system. Java will be required indeed, but I bet most people have it already.

On the other hand people might want to run tests with their own remote IMAP server.

2024-06-04 09:27 UTC, pabzm commented on tests/MessageRendering/MessageRenderingTestCase.php
> +        $rcmail->login('test', 'pass', 'tls://localhost');
This setup uses docker to run dovecot, you don't have to install it locally. Don't you think docker is an acceptable dependency for a test suite?

2024-06-04 09:28 UTC, pabzm commented on tests/MessageRendering/MessageRenderingTestCase.php
> +    protected function run_and_get_html_output_domxpath(string $msg_id): \DOMXPath
Ok, so we continue snake_case if the file already contains some, but if not we default to CamelCase?

Only in tests, or also in other code?

(Sorry for insisting, I want to understand thoroughly.)

2024-06-20 13:54 UTC, pabzm commented on tests/MessageRendering/MessageRenderingTestCase.php
> +        $rcmail->login('test', 'pass', 'tls://localhost');
@alecpl Could you let me know if you think docker (or a similar container setup) is an acceptable dependency?

I don't really like to sudo-execute a binary downloaded from the internet, and would much prefer a container. We could still use greenmail, if you prefer that: https://hub.docker.com/r/greenmail/standalone

2024-12-19 18:01 UTC, merged