Missing polish translation for "keep formatting"
roundcube/roundcubemail pull request #9493
Opened 2024-06-10 09:39 UTC by KrzysztofWWW

Missing polish translation for "keep formatting"

2024-06-12 08:33 UTC, pabzm requested changes
Thank you for your contribution! Besides the line ordering this looks good to me and could be merged!

2024-06-12 08:33 UTC, pabzm commented on program/localization/pl_PL/labels.inc
> +$labels['keepformatting'] = 'Zachowaj formatowanie';
Please move this line below the line translating `dsn` (because that's where the other translations have it).

2024-06-12 08:36 UTC, alecpl commented
Localization need to be updated on Transifex otherwise the change will be overwritten next time we sync localizations.

2024-06-12 10:00 UTC, KrzysztofWWW commented on program/localization/pl_PL/labels.inc
> +$labels['keepformatting'] = 'Zachowaj formatowanie';
I've commited the changes

2024-06-12 12:35 UTC, pabzm commented
@KrzysztofWWW Sorry for that, I should have known it and not instruct you do reorder. Are you willing to enter the translation at transifex.com? If not, I/we can do that, too.

For details on how to do it, see https://github.com/roundcube/roundcubemail/wiki/Languages

2024-06-12 13:24 UTC, eveneme commented
> Localization need to be updated on Transifex otherwise the change will be overwritten next time we sync localizations.

I've been waiting a month for my Roundcube Transifex account to be accepted...  Emial: michalborutta@gmail.com

2024-06-13 20:08 UTC, KrzysztofWWW commented
@pabzm I'm not familiar with trasifex.com so if you could do this I would be grateful.

2024-06-16 06:30 UTC, merged