Added PluginAPI hooks for message_move and message_delete
roundcube/roundcubemail pull request #9501
Opened 2024-06-14 11:41 UTC by JE4GLE

This pull request implements the requested PluginAPI Hooks from ticket #9499.

_The wiki needs to be updated, once the change is released._

## Wiki

### message_delete

Triggered when a message is deleted.
The message is identified by the `uid`.

_Arguments:_
  * uid
  * mailbox: _The mailbox the message is deleted from_

_Return values:_
  none.

### message_move

Triggered when a message is moved from one folder to another.
The message is identified by the `uid`. The `mailbox` and `target` value may be equal, if it is moved to the same folder.

_Arguments:_
  * uid
  * mailbox: _The mailbox the message is moved from_
  * target: _The mailbox the message is moved to_

_Return values:_
  none.

2024-06-14 11:47 UTC, alecpl commented
I think better place to put these will be `rcube_imap`. Also, for your use-case this might be enough, but maybe we should take the `abort` flag into consideration.

2024-06-14 12:17 UTC, alecpl commented
I guess it depends what you want to do with it. For example `message_saved` is in `rcube_imap`. It's obvious why it makes sense to keep these closer to the storage class. `rcube_imap::move_message()` might be called from various places, e.g. `folder_purge` action uses it too. So, you can handle different move message actions from a single place.

Putting these in actions would make sense if you wanted to interfere in any way with the UI, I suppose.

2024-06-14 12:35 UTC, JE4GLE commented
Thank you, I adjusted the code accordingly!

2024-06-14 12:39 UTC, alecpl commented on program/lib/Roundcube/rcube_imap.php
> +        foreach ($uids as $uid) {
`$uids` is a string here.

2024-06-14 13:20 UTC, alecpl commented on program/lib/Roundcube/rcube_imap.php
> +        $uidsArray = explode(',', $uids);
Nope. $uids can be "*" or "1:*" or "1-2". I suggest to skip the loop and pass $uids as is to the hook. No aborted uids. Just return (false or []) on abort.

2024-06-14 15:38 UTC, alecpl requested changes

2024-06-14 15:38 UTC, alecpl commented on program/lib/Roundcube/rcube_imap.php
> +        $plugin = $this->plugins->exec_hook('message_delete', ['mailbox' => $folder, 'uids' => $uids]);
I know for example `message_read` hook has 'mailbox' argument, but I prefer 'folder' that is used in other hooks.

2024-06-14 15:38 UTC, alecpl commented on program/lib/Roundcube/rcube_imap.php
> +        if (isset($plugin['abort']) && $plugin['abort']) {
No need to use isset(), 'abort' is always set.

2024-06-14 15:38 UTC, alecpl commented on program/lib/Roundcube/rcube_imap.php
> +        $plugin = $this->plugins->exec_hook('message_move', ['mailbox' => $from_mbox, 'target' => $to_mbox, 'uids' => $uids]);
How about 'from' and 'to' or 'source_folder' and 'target_folder'?

2024-06-16 12:08 UTC, alecpl commented on program/lib/Roundcube/rcube_imap.php
> +        $plugin = $this->plugins->exec_hook('message_move', ['from_folder' => $from_mbox, 'target_folder' => $to_mbox, 'uids' => $uids]);
All right, we're almost there. If we use 'target_folder' then we should use 'source_folder' or just 'folder' and 'target'. Or even just 'from' and 'to' like in the variable names.

2024-06-17 10:15 UTC, JE4GLE commented
Thank you for all your helpful comments! I hope the PR can be merged quickly :)

2024-06-19 16:15 UTC, merged