Make pgpmime-support known after Mailvelope init
roundcube/roundcubemail pull request #9551
Opened 2024-07-16 09:49 UTC by pabzm

The support for pgpmime was only checked initially after the login. If a user e.g. authorizes a domain in Mailvelope only after a login, Mailvelope now instantly works, instead of (silently and undocumentedly) requireing a logout+login-cycle.

2024-07-21 09:50 UTC, alecpl commented
This does not look like a best solution. If you take a look at how `mailvelope_load()` is invoked you'll see that  it is only when Mailvelope is enabled. There's no need to call `pgpmime_support_check()`. It will not set the `env` variable in some circumstances.

I see three solutions:
1. I think we should just set `rcmail.env.browser_capabilities.pgpmime = 1` in `mailvelope_load()`.
2. Unset `$_SESSION['browser_caps']['pgpmime']` when enabling Mailvelope.
3. Always check for pgpmime capability as it is not a heavy check (in `browser_capabilities_check()`).

2nd is not great as it will require an extra http request. From 1. and 3. I have no preference.

2024-07-23 10:32 UTC, pabzm commented
I chose the first alternative since it's the most straightforward. Thank you for the hint on my misunderstanding of the code!

2024-07-24 17:11 UTC, alecpl requested changes

2024-07-24 17:11 UTC, alecpl commented on program/js/app.js
> +        this.env.browser_capabilities.pgpmime = 1
Missing semicolon.

2024-07-24 17:24 UTC, pabzm commented on program/js/app.js
> +        this.env.browser_capabilities.pgpmime = 1
Fixed 👍

2024-07-25 06:05 UTC, merged