Use server date year as copyright end year
roundcube/roundcubemail pull request #9603
Opened 2024-08-24 19:27 UTC by stefan-muc

To not have to update it every year or getting it wrong as in 1.6.8 simply use the year of the server date as copyright end year

2024-08-25 05:34 UTC, alecpl commented
I think we should just remove the year(s), as we did in source file headers some time ago. Copyright years do not provide much value. And the info can be derived from git history.

2024-08-28 09:52 UTC, pabzm commented
@stefan-muc Thank you for your contribution! As you see it invoked a thought to solve the topic differently. Would you be willing to remove the years instead of changing them? Then we could merge this!

2024-09-01 15:30 UTC, stefan-muc commented
Sure I'm willing! I just thought that simply removing it can be done by the team itself - but here you are with a changed pull request.

2024-09-02 12:57 UTC, pabzm commented
Of course we could have done it ourselves, but I didn't want to steal the opportunity of a contribution from you. :)

Thank you!

2024-09-02 12:59 UTC, pabzm requested changes

2024-09-02 12:59 UTC, pabzm commented on installer/index.php
> +  Installer &copy; by The Roundcube Dev Team – Published under the GNU Public License;&nbsp;
Could you please re-add the word "Copyright" (since is used in the other places as well in combination with the symbol).

2024-09-02 19:30 UTC, stefan-muc commented on installer/index.php
> +  Installer &copy; by The Roundcube Dev Team – Published under the GNU Public License;&nbsp;
Sorry, somehow I missed this. Re-added now!

2024-09-03 08:03 UTC, pabzm approved these changes
Thank you! 👍

2024-09-17 21:05 UTC, pabzm commented
@alecpl I'll merge this on Monday unless you object. (The CI errors are unrelated, don't happen locally neither.)

2024-09-18 11:51 UTC, merged