add invalid and error details to vcard import report
roundcube/roundcubemail pull request #9605
Opened 2024-08-25 09:41 UTC by johndoh

for #9591

currently there are 2 silent error cases on vcard import, invalid (fails roundcube contact validation) and error (its valid but i didnt insert for some reason e.g. plugin prevented it) this adds messages about those to the screen.

![Untitled-1](https://github.com/user-attachments/assets/240ce7dc-dd67-45cc-8469-ffe76f2d0c96)

2024-09-12 09:55 UTC, pabzm requested changes
Thank you for the contribution! I really appreciate your attention to issues related to "your" topic!

2024-09-12 09:55 UTC, pabzm commented on program/actions/contacts/import.php
> +                        self::$stats->invalid_names[] = $vcard->displayname ?: $email;
Could you insert a check to handle the case in which both, `displayname` and `$email` might be `null` or empty?

Also if you rebase onto the latest "master"-branch you should get rid of the failing tests with PHP8.4.

2024-09-14 05:25 UTC, johndoh commented on program/actions/contacts/import.php
> +                        self::$stats->invalid_names[] = $vcard->displayname ?: $email;
quite right. I changed it to use `rcube_addressbook::compose_display_name()` which will always return a value because to get this far there must be at least one of `displayname`, `surname`, `firstname` or `email` and this function checks all of those.

2024-09-16 13:16 UTC, pabzm approved these changes
Looks good to me, thank you!

2024-09-18 12:05 UTC, alecpl approved these changes
Approved with some comments.

2024-09-18 12:05 UTC, alecpl commented on program/localization/en_US/messages.inc
> +$messages['importconfirmerrors'] = '<b>Failed to import $errors valid contacts</b>';
We should probably get rid of HTML tags from all these three messages.

2024-09-18 12:05 UTC, alecpl commented on program/actions/contacts/import.php
> +        $vars['names'] = $vars['skipped_names'] = $vars['invalid_names'] = $vars['error_names'] = '';
This line is probably unnecessary. Also, we should probably not use "magic" `get_object_vars()` and assign the `$vars` elements explicitly.

2024-09-18 15:23 UTC, johndoh commented on program/localization/en_US/messages.inc
> +$messages['importconfirmerrors'] = '<b>Failed to import $errors valid contacts</b>';
I think removing the `<b>` tags would be a breaking change because the formatting should be moved to the skin to do this properly. I can work on this in a separate PR.

2024-09-18 15:27 UTC, johndoh commented on program/actions/contacts/import.php
> +        $vars['names'] = $vars['skipped_names'] = $vars['invalid_names'] = $vars['error_names'] = '';
are you happy for me to replace `self::$stats = new stdClass();` with a new specific class like say `rcmail_action_contacts_import_stats` and then we can have something like a `get_vars()` method to initialize `$vars`.

2024-09-18 15:58 UTC, alecpl commented on program/actions/contacts/import.php
> +        $vars['names'] = $vars['skipped_names'] = $vars['invalid_names'] = $vars['error_names'] = '';
I'm fine with `StdClass`, I don't like filling needlessly `$vars` with all properties while we need one at a time. And we don't use *_names variants in localized messages. I would probably remove `$vars` completely.

2024-09-18 18:09 UTC, johndoh commented on program/actions/contacts/import.php
> +        $vars['names'] = $vars['skipped_names'] = $vars['invalid_names'] = $vars['error_names'] = '';
I have removed `$vars` and also the `nr` passed to `gettext` as that is meaningless.

2024-11-20 08:51 UTC, pabzm commented
@johndoh Would you add a line to the Changelog? (I can do it as well but would prefer to have it as part of the PR.)

2024-11-20 19:25 UTC, johndoh commented
I've added a changelog entry. If you don't like the text or its in the wrong place its no problem.

2024-12-02 07:08 UTC, merged

2024-12-02 07:08 UTC, pabzm commented
@johndoh Thanks again for your contribution! 🙏