Allow hiding "Keep formatting" in "dont_override" config
roundcube/roundcubemail pull request #9704
Opened 2024-11-15 08:57 UTC by JE4GLE

Fixes #9703 
According to [this blog entry](https://kolabian.wordpress.com/2021/11/07/a-few-small-improvements/), "Keep formatting" is for power users and therefore it would be nice to be removable.

2024-11-18 10:52 UTC, pabzm commented
Thank you for the PR! Please rebase onto the latest state of the "master" branch and remove the translation-related commits.

2024-11-19 14:35 UTC, alecpl commented
This is incomplete. Well, maybe a rare case, but what if you set `keep_formatting=true`, and then add it to `dont_override`? A small change in `rcmail_action_mail_send::run()` is needed to support this case.

2024-11-20 07:10 UTC, alecpl requested changes

2024-11-20 07:10 UTC, alecpl commented on program/actions/mail/send.php
> +            $keepformatting = false;
This is wrong. It should be 
```php
if (in_array('keep_formatting', $rcmail->config->get('dont_override', []))) {
    $keepformatting = !empty($rcmail->config->get('keep_formatting'));
} else {
    $keepformatting = !empty($_POST['_keepformatting']);
}
```

2024-11-20 07:12 UTC, pabzm commented on program/actions/mail/send.php
> +            $keepformatting = false;
Exactly my thought. The configured value must be honoured. 👍

2024-11-20 08:46 UTC, JE4GLE commented on program/actions/mail/send.php
> +            $keepformatting = false;
Thank you, I didn't know, there was a configurable value.

2024-11-20 08:52 UTC, alecpl commented on program/actions/mail/send.php
> +            $keepformatting = false;
Oops. I thought there was, but you're right. However, I'd leave it as-is. We may introduce the option in future.

2024-11-20 08:54 UTC, pabzm approved these changes
Looks good to me!

@JE4GLE  We need a line in the Changelog, would you maybe add one?

2024-11-20 09:04 UTC, pabzm commented
/remind me to merge on Dec 4th

2024-11-20 09:17 UTC, cebe commented on program/actions/mail/send.php
> +        if (in_array('keep_formatting', $rcmail->config->get('dont_override', []))) {
```suggestion
        if (in_array('keep_formatting', $rcmail->config->get('dont_override', []), true)) {
```

2024-11-20 10:40 UTC, cebe approved these changes

2024-11-20 13:15 UTC, pabzm commented on program/actions/mail/send.php
> +        if (in_array('keep_formatting', $rcmail->config->get('dont_override', []))) {
To clarify: I know what the change technically does. But I don't appreciate someone jumping in from the sidelines without communicating. Please respect the development work and talk to us.

2024-11-20 13:21 UTC, pabzm requested changes
I'd prefer to mention the actual config mechanism in the Changelog

2024-11-20 16:18 UTC, pabzm approved these changes
Thank you very much! 👍

2024-11-20 16:19 UTC, pabzm commented
/remind me to merge on 2024-12-04

2024-12-23 13:25 UTC, closed without merging